import { CameraProfile, CameraType } from '../types';
import { defaultAdjustments, defaultHSL, defaultCurves } from './defaultAdjustments';

export const CAMERA_PROFILES: CameraProfile[] = [
  {
    id: 'disposable',
    name: 'Disposable',
    subtitle: '90s Single-Use Flash Cam',
    tagline: 'Warm amber glow, 90s LED date stamp, flash falloff and vintage film grain',
    accentColor: '#F59E0B',
    dateStampFormat: 'led-orange',
    featuresDescription: ['90s Orange LED Date Stamp', 'Direct Flash Falloff Vignette', 'Warm Amber Highlights', 'Fine Disposable Grain'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'disposable',
      presetId: 'camera-disposable',
      exposure: 0.1,
      contrast: 0.18,
      highlights: -0.15,
      shadows: 0.15,
      temperature: 0.22,
      tint: 0.08,
      saturation: 0.12,
      vibrance: 0.2,
      grainAmount: 0.26,
      grainSize: 1.1,
      vignetteAmount: 0.25,
      lightLeakType: 'corner-burn',
      lightLeakAmount: 0.22,
      hsl: {
        ...defaultHSL,
        orange: { hue: -0.05, saturation: 0.15, luminance: 0.06 },
        yellow: { hue: -0.1, saturation: 0.12, luminance: 0.04 },
      },
      curves: {
        ...defaultCurves,
        master: [{ x: 0, y: 0.06 }, { x: 0.28, y: 0.26 }, { x: 0.72, y: 0.78 }, { x: 1, y: 0.98 }],
        red: [{ x: 0, y: 0.03 }, { x: 0.5, y: 0.53 }, { x: 1, y: 1 }],
      },
    },
  },
  {
    id: 'fling35',
    name: 'fling35',
    subtitle: 'Summer 35mm Point & Shoot',
    tagline: 'Punchy saturated colors, sun-kissed golden flare, and retro 35mm frame index',
    accentColor: '#EF4444',
    dateStampFormat: 'none',
    featuresDescription: ['FLING 35 - 27 EXP Film Stamp', 'Frame Counter Index [18A]', 'Golden Flare Streak', 'Vibrant Beach Tones'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'fling35',
      presetId: 'camera-fling35',
      exposure: 0.06,
      contrast: 0.22,
      highlights: -0.1,
      shadows: 0.12,
      temperature: 0.18,
      tint: 0.04,
      saturation: 0.24,
      vibrance: 0.28,
      grainAmount: 0.22,
      grainSize: 1.2,
      lightLeakType: 'side-flare',
      lightLeakAmount: 0.35,
      vignetteAmount: 0.18,
      curves: {
        ...defaultCurves,
        master: [{ x: 0, y: 0.04 }, { x: 0.25, y: 0.22 }, { x: 0.75, y: 0.82 }, { x: 1, y: 1 }],
      },
    },
  },
  {
    id: 'kodak-gold',
    name: 'kodak gold',
    subtitle: 'Kodak Gold 200 Warm Film',
    tagline: 'Warm golden amber highlights, rich yellow-red palette, authentic film edge markings',
    accentColor: '#D97706',
    dateStampFormat: 'none',
    featuresDescription: ['KODAK GOLD 200 Edge Markings', 'Golden Amber Warmth', 'Classic Color S-Curve', 'Smooth Halide Grain'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'kodak-gold',
      presetId: 'camera-kodak-gold',
      exposure: 0.04,
      contrast: 0.14,
      highlights: -0.18,
      shadows: 0.2,
      temperature: 0.3,
      tint: 0.05,
      saturation: 0.14,
      vibrance: 0.2,
      grainAmount: 0.2,
      grainSize: 1.0,
      glowAmount: 0.12,
      vignetteAmount: 0.15,
      hsl: {
        ...defaultHSL,
        yellow: { hue: -0.12, saturation: 0.2, luminance: 0.05 },
        orange: { hue: -0.06, saturation: 0.18, luminance: 0.08 },
        blue: { hue: -0.08, saturation: -0.1, luminance: -0.05 },
      },
      curves: {
        ...defaultCurves,
        master: [{ x: 0, y: 0.05 }, { x: 0.3, y: 0.28 }, { x: 0.7, y: 0.76 }, { x: 1, y: 0.98 }],
        red: [{ x: 0, y: 0.02 }, { x: 0.5, y: 0.54 }, { x: 1, y: 1 }],
        blue: [{ x: 0, y: 0 }, { x: 0.5, y: 0.46 }, { x: 1, y: 0.94 }],
      },
    },
  },
  {
    id: 'klasse',
    name: 'klasse',
    subtitle: 'Fujifilm Klasse 38mm F2.6',
    tagline: 'High-end compact film camera, sharp microcontrast, pristine natural skin tones',
    accentColor: '#4B5563',
    dateStampFormat: 'none',
    featuresDescription: ['FUJIFILM KLASSE 38mm f/2.6 Badge', 'Pro Aperture/Shutter HUD', 'Ultra-Sharp Microcontrast', 'Natural Skin Tones'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'klasse',
      presetId: 'camera-klasse',
      exposure: 0.02,
      contrast: 0.16,
      highlights: -0.12,
      shadows: 0.08,
      clarity: 0.22,
      temperature: -0.04,
      tint: 0.02,
      saturation: 0.06,
      vibrance: 0.12,
      grainAmount: 0.14,
      grainSize: 0.9,
      glowAmount: 0.08,
      vignetteAmount: 0.12,
    },
  },
  {
    id: 'polaroid',
    name: 'Polaroid',
    subtitle: 'Vintage 600 Instant Film',
    tagline: 'Classic white instant frame, bottom chin, cool cyan shadows and creamy highlights',
    accentColor: '#3B82F6',
    dateStampFormat: 'none',
    featuresDescription: ['Classic White Instant Frame with Chin', 'Polaroid 600 Rainbow Badge', 'Cyan Shadow Shift', 'Matte Film Fade'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'polaroid',
      presetId: 'camera-polaroid',
      frameType: 'polaroid',
      exposure: 0.05,
      contrast: -0.08,
      highlights: -0.22,
      shadows: 0.28,
      whites: -0.1,
      blacks: 0.16,
      temperature: 0.12,
      tint: -0.06,
      saturation: -0.05,
      vibrance: 0.1,
      grainAmount: 0.24,
      glowAmount: 0.16,
      vignetteAmount: 0.2,
      hsl: {
        ...defaultHSL,
        cyan: { hue: 0.08, saturation: 0.15, luminance: 0.05 },
        blue: { hue: 0.05, saturation: -0.12, luminance: 0.04 },
      },
      curves: {
        ...defaultCurves,
        master: [{ x: 0, y: 0.12 }, { x: 0.35, y: 0.32 }, { x: 0.75, y: 0.78 }, { x: 1, y: 0.94 }],
        blue: [{ x: 0, y: 0.08 }, { x: 0.5, y: 0.52 }, { x: 1, y: 0.95 }],
      },
    },
  },
  {
    id: 'paradiso',
    name: 'paradiso',
    subtitle: 'Riviera Summer 35mm',
    tagline: 'Sun-drenched Mediterranean warmth, radiant teal and golden orange harmony',
    accentColor: '#06B6D4',
    dateStampFormat: 'none',
    featuresDescription: ['PARADISO 35mm Riviera Stamp', 'Sun-Kissed Golden Highlights', 'Teal Sea Shadows', 'Dream Summer Bloom'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'paradiso',
      presetId: 'camera-paradiso',
      exposure: 0.08,
      contrast: 0.2,
      highlights: -0.15,
      shadows: 0.18,
      temperature: 0.24,
      tint: -0.02,
      saturation: 0.18,
      vibrance: 0.26,
      glowAmount: 0.22,
      lightLeakType: 'sunset',
      lightLeakAmount: 0.25,
      grainAmount: 0.16,
      hsl: {
        ...defaultHSL,
        orange: { hue: -0.08, saturation: 0.25, luminance: 0.08 },
        cyan: { hue: 0.12, saturation: 0.2, luminance: -0.04 },
        blue: { hue: -0.06, saturation: -0.15, luminance: -0.08 },
      },
    },
  },
  {
    id: 'calagold',
    name: 'calagold',
    subtitle: 'California Golden Hour 35mm',
    tagline: 'Deep bronze shadows, sunburst golden rays, Pacific Coast aesthetic',
    accentColor: '#B45309',
    dateStampFormat: 'none',
    featuresDescription: ['CALIFORNIA GOLD • 35MM Stamp', 'Pacific Coast Sunset Warmth', 'Deep Bronze Tones', 'Sunburst Light Flare'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'calagold',
      presetId: 'camera-calagold',
      exposure: 0.06,
      contrast: 0.16,
      highlights: -0.2,
      shadows: 0.24,
      temperature: 0.36,
      tint: 0.06,
      saturation: 0.14,
      vibrance: 0.22,
      glowAmount: 0.2,
      lightLeakType: 'sunset',
      lightLeakAmount: 0.3,
      grainAmount: 0.18,
      vignetteAmount: 0.18,
    },
  },
  {
    id: 'sunshot07',
    name: 'sunshot07',
    subtitle: '2007 Beach Digicam',
    tagline: 'Y2K direct flash, vibrant primary tones, yellow digital timestamp and battery HUD',
    accentColor: '#FACC15',
    dateStampFormat: 'y2k-yellow',
    featuresDescription: ['2007 Yellow Date Clock [2007.07.18]', 'SUNSHOT 07 DIGITAL • 7.1MP Stamp', 'Battery & Flash Status HUD', 'Crisp Digicam Flash Pop'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'sunshot07',
      presetId: 'camera-sunshot07',
      exposure: 0.12,
      contrast: 0.24,
      highlights: 0.08,
      shadows: -0.06,
      clarity: 0.18,
      temperature: 0.08,
      saturation: 0.2,
      vibrance: 0.24,
      glowAmount: 0.14,
      vignetteAmount: 0.14,
      grainAmount: 0.12,
    },
  },
  {
    id: 'solare17',
    name: 'solare17',
    subtitle: 'Indie Sunflare Analog',
    tagline: 'Golden solar flare streaks, soft matte blacks, nostalgic warm mood',
    accentColor: '#EA580C',
    dateStampFormat: 'none',
    featuresDescription: ['SOLARE 17 • ANALOG Corner Stamp', 'Golden Solar Flare Streaks', 'Faded Velvet Matte Blacks', 'Organic Dust & Scratches'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'solare17',
      presetId: 'camera-solare17',
      exposure: 0.05,
      contrast: -0.05,
      highlights: -0.18,
      shadows: 0.25,
      blacks: 0.14,
      temperature: 0.28,
      tint: 0.06,
      saturation: 0.08,
      vibrance: 0.18,
      lightLeakType: 'retro-streak',
      lightLeakAmount: 0.38,
      dustType: 'fine-specks',
      dustAmount: 0.2,
      grainAmount: 0.2,
    },
  },
  {
    id: 'prima',
    name: 'Prima',
    subtitle: 'Canon Prima 90s Compact',
    tagline: '90s point-and-shoot direct flash look with classic red LED date stamp',
    accentColor: '#DC2626',
    dateStampFormat: 'led-red',
    featuresDescription: ['90s Red LED Date Stamp [05 12 \'94]', 'CANON PRIMA AF Stamp', 'Direct Flash Punch', 'Classic 90s Color Tone'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'prima',
      presetId: 'camera-prima',
      exposure: 0.08,
      contrast: 0.22,
      highlights: -0.1,
      shadows: 0.1,
      temperature: 0.14,
      tint: 0.04,
      saturation: 0.16,
      vibrance: 0.2,
      grainAmount: 0.22,
      vignetteAmount: 0.22,
      glowAmount: 0.12,
    },
  },
  {
    id: 'novagold',
    name: 'novagold',
    subtitle: 'Nova Gold 400 Celestial',
    tagline: 'Celestial golden tones, glowing highlights, soft vintage portrait warmth',
    accentColor: '#F59E0B',
    dateStampFormat: 'none',
    featuresDescription: ['NOVA GOLD 400 Starburst Seal', 'Glowing Celestial Highlights', 'Velvety Warm Portraits', 'Fine Golden Grain'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'novagold',
      presetId: 'camera-novagold',
      exposure: 0.06,
      contrast: 0.12,
      highlights: -0.22,
      shadows: 0.2,
      temperature: 0.32,
      tint: 0.05,
      saturation: 0.1,
      vibrance: 0.22,
      glowAmount: 0.25,
      grainAmount: 0.18,
    },
  },
  {
    id: 'moka-v',
    name: 'moka v',
    subtitle: 'Dark Roast Coffee 400',
    tagline: 'Deep chocolate undertones, creamy latte highlights, rich earthy matte finish',
    accentColor: '#78350F',
    dateStampFormat: 'none',
    featuresDescription: ['MOKA V • 400 Minimalist Stamp', 'Rich Espresso Shadows', 'Creamy Latte Highlights', 'Earthy Velvet Matte Tones'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'moka-v',
      presetId: 'camera-moka-v',
      exposure: 0.02,
      contrast: 0.2,
      highlights: -0.25,
      shadows: 0.16,
      whites: 0.04,
      blacks: -0.08,
      temperature: 0.26,
      tint: 0.06,
      saturation: 0.08,
      vibrance: 0.14,
      grainAmount: 0.24,
      vignetteAmount: 0.24,
      hsl: {
        ...defaultHSL,
        orange: { hue: -0.06, saturation: 0.18, luminance: 0.04 },
        green: { hue: 0.2, saturation: -0.3, luminance: -0.1 },
        blue: { hue: -0.1, saturation: -0.3, luminance: -0.15 },
      },
    },
  },
  {
    id: '5cam',
    name: '5cam',
    subtitle: '3D Lenticular Multi-Lens',
    tagline: '5-lens stereo camera effect with chromatic dispersion and 3D frame notches',
    accentColor: '#8B5CF6',
    dateStampFormat: 'none',
    featuresDescription: ['5CAM 3D STEREO 5-Lens Badge [1][2][3][4][5]', '3D Chromatic Prism Offset', 'Lenticular Frame Notches', 'Stereoscopic Color Pop'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: '5cam',
      presetId: 'camera-5cam',
      exposure: 0.04,
      contrast: 0.18,
      prismAmount: 0.45,
      saturation: 0.15,
      vibrance: 0.22,
      grainAmount: 0.18,
      vignetteAmount: 0.15,
    },
  },
  {
    id: 'asteria',
    name: 'asteria',
    subtitle: 'Celestial Midnight 800',
    tagline: 'Starlit ethereal blues, glowing magenta highlights, soft celestial bloom',
    accentColor: '#6366F1',
    dateStampFormat: 'none',
    featuresDescription: ['ASTERIA CELESTIAL • 800 Star Badge', 'Midnight Indigo Shadows', 'Radiant Magenta Star Glow', 'Ethereal Diffusion Halo'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'asteria',
      presetId: 'camera-asteria',
      exposure: 0.04,
      contrast: 0.16,
      highlights: -0.12,
      shadows: 0.14,
      temperature: -0.18,
      tint: 0.22,
      saturation: 0.12,
      vibrance: 0.24,
      glowAmount: 0.3,
      glowRadius: 0.6,
      grainAmount: 0.16,
      hsl: {
        ...defaultHSL,
        blue: { hue: 0.05, saturation: 0.22, luminance: 0.04 },
        purple: { hue: -0.05, saturation: 0.28, luminance: 0.08 },
        magenta: { hue: 0.08, saturation: 0.3, luminance: 0.1 },
      },
    },
  },
  {
    id: 'natura',
    name: 'Natura',
    subtitle: 'Fujifilm Natura 1600',
    tagline: 'Legendary high-speed ambient light film, cool pastel greens, fine fast grain',
    accentColor: '#10B981',
    dateStampFormat: 'none',
    featuresDescription: ['FUJIFILM NATURA 1600 • NP Stamp', 'Natural Ambient Light Color Balance', 'Pastel Greens & Soft Skin Tones', 'Authentic High-Speed 1600 Grain'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'natura',
      presetId: 'camera-natura',
      exposure: 0.1,
      contrast: 0.08,
      highlights: -0.2,
      shadows: 0.25,
      temperature: -0.08,
      tint: -0.04,
      saturation: -0.04,
      vibrance: 0.15,
      grainAmount: 0.28,
      grainSize: 1.2,
      glowAmount: 0.18,
      hsl: {
        ...defaultHSL,
        green: { hue: 0.12, saturation: 0.14, luminance: 0.06 },
        orange: { hue: 0.04, saturation: 0.1, luminance: 0.08 },
      },
    },
  },
  {
    id: 'aurea',
    name: 'aurea',
    subtitle: 'Aurea Golden Aura 200',
    tagline: 'Radiant golden aura halation, soft shimmering highlights, warm diffusion bloom',
    accentColor: '#F59E0B',
    dateStampFormat: 'none',
    featuresDescription: ['AUREA GLOW • 200 Seal', 'Radiant Golden Aura Diffusion', 'Luminous Highlight Halation', 'Warm Shimmering Glow'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'aurea',
      presetId: 'camera-aurea',
      exposure: 0.08,
      contrast: 0.1,
      highlights: -0.15,
      shadows: 0.18,
      temperature: 0.28,
      tint: 0.04,
      saturation: 0.08,
      vibrance: 0.2,
      glowAmount: 0.4,
      glowRadius: 0.65,
      grainAmount: 0.14,
    },
  },
  {
    id: 'fuji400',
    name: 'fuji400',
    subtitle: 'Fujicolor Superia 400',
    tagline: 'Crisp emerald greens, cool pastel tones, vibrant balanced daylight film response',
    accentColor: '#059669',
    dateStampFormat: 'none',
    featuresDescription: ['FUJICOLOR SUPERIA 400 Edge Stamp', 'Process CN-16 • 36 EXP Marking', 'Crisp Emerald Greens', 'Fine Daylight Film Texture'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'fuji400',
      presetId: 'camera-fuji400',
      exposure: 0.04,
      contrast: 0.15,
      highlights: -0.14,
      shadows: 0.16,
      temperature: -0.06,
      tint: -0.08,
      saturation: 0.12,
      vibrance: 0.2,
      grainAmount: 0.18,
      grainSize: 1.0,
      glowAmount: 0.1,
      hsl: {
        ...defaultHSL,
        green: { hue: 0.18, saturation: 0.22, luminance: 0.06 },
        cyan: { hue: 0.08, saturation: 0.15, luminance: 0.02 },
        red: { hue: 0.04, saturation: 0.16, luminance: 0.04 },
      },
    },
  },
  {
    id: 'velour',
    name: 'velour',
    subtitle: 'Velour Luxury 100',
    tagline: 'Deep plum and ruby red shadows, ultra-smooth creamy microcontrast',
    accentColor: '#9D174D',
    dateStampFormat: 'none',
    featuresDescription: ['VELOUR 100 • FINE GRAIN Luxury Stamp', 'Deep Plum & Ruby Shadows', 'Ultra-Smooth Creamy Contrast', 'Editorial Velvet Finish'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'velour',
      presetId: 'camera-velour',
      exposure: 0.02,
      contrast: 0.22,
      highlights: -0.18,
      shadows: 0.12,
      temperature: 0.14,
      tint: 0.18,
      saturation: 0.14,
      vibrance: 0.2,
      grainAmount: 0.16,
      vignetteAmount: 0.22,
    },
  },
  {
    id: 'lunaria',
    name: 'lunaria',
    subtitle: 'Lunaria Moonlit B&W 400',
    tagline: 'Silvery luminous monochrome with cool blue undertones, deep silver tones',
    accentColor: '#94A3B8',
    dateStampFormat: 'none',
    featuresDescription: ['LUNARIA 400 • MONOCHROME Silver Stamp', 'Cool Moonlit Silver Undertones', 'Luminous Highlight Glow', 'Fine Silver Halide Grain'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'lunaria',
      presetId: 'camera-lunaria',
      saturation: -1.0,
      vibrance: -1.0,
      contrast: 0.22,
      highlights: -0.1,
      shadows: 0.14,
      whites: 0.08,
      blacks: -0.06,
      clarity: 0.2,
      grainAmount: 0.2,
      grainSize: 1.0,
      glowAmount: 0.15,
      vignetteAmount: 0.18,
    },
  },
  {
    id: 'velvia',
    name: 'velvia',
    subtitle: 'Fujichrome Velvia 50',
    tagline: 'Legendary professional landscape slide film, ultra-saturated vivid blues & reds',
    accentColor: '#2563EB',
    dateStampFormat: 'none',
    featuresDescription: ['FUJICHROME VELVIA 50 • RVP Margin Stamp', 'Ultra-Saturated Vivid Blues & Reds', 'High Dynamic Contrast Punch', 'Professional Slide Clarity'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'velvia',
      presetId: 'camera-velvia',
      exposure: 0.02,
      contrast: 0.28,
      highlights: -0.1,
      shadows: 0.05,
      clarity: 0.24,
      temperature: 0.02,
      tint: 0.04,
      saturation: 0.35,
      vibrance: 0.38,
      grainAmount: 0.12,
      vignetteAmount: 0.15,
      hsl: {
        ...defaultHSL,
        blue: { hue: 0.02, saturation: 0.35, luminance: -0.06 },
        green: { hue: 0.1, saturation: 0.3, luminance: -0.04 },
        red: { hue: 0.02, saturation: 0.32, luminance: 0.05 },
      },
    },
  },
  {
    id: 'ilford',
    name: 'Ilford',
    subtitle: 'Ilford HP5 Plus 400',
    tagline: 'Classic British black & white film, rich silver halide contrast, punchy grain',
    accentColor: '#1E293B',
    dateStampFormat: 'none',
    featuresDescription: ['ILFORD HP5 PLUS 400 Border Stamp', 'Safety Film • Ilford England Markings', 'Rich Silver Halide Contrast', 'Classic Medium Film Grain'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'ilford',
      presetId: 'camera-ilford',
      frameType: 'film-35mm',
      saturation: -1.0,
      vibrance: -1.0,
      contrast: 0.32,
      highlights: -0.15,
      shadows: 0.1,
      whites: 0.12,
      blacks: -0.12,
      clarity: 0.26,
      grainAmount: 0.3,
      grainSize: 1.2,
      vignetteAmount: 0.22,
    },
  },
  {
    id: 'curva',
    name: 'curva',
    subtitle: 'Anamorphic Cinema 2.39:1',
    tagline: 'Cinematic widescreen 2.39:1 matte bars, horizontal blue streak flare, barrel glow',
    accentColor: '#38BDF8',
    dateStampFormat: 'none',
    featuresDescription: ['CURVA ANAMORPHIC • 2.39:1 Stamp', 'Cinematic Widescreen Matte Bars', 'Horizontal Blue Optical Streak', 'Moody Cinema Color Grade'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'curva',
      presetId: 'camera-curva',
      cropAspect: '16:9',
      exposure: 0.02,
      contrast: 0.2,
      highlights: -0.18,
      shadows: 0.15,
      temperature: -0.08,
      tint: 0.02,
      saturation: 0.08,
      vibrance: 0.18,
      lightLeakType: 'retro-streak',
      lightLeakAmount: 0.35,
      prismAmount: 0.3,
      vignetteAmount: 0.25,
      glowAmount: 0.15,
    },
  },
  {
    id: 'camcorder',
    name: 'camcorder',
    subtitle: '90s Hi8 Handy Video Cam',
    tagline: '90s Camcorder HUD with ● REC, SP, battery indicator, tape counter and scanlines',
    accentColor: '#22C55E',
    dateStampFormat: 'camcorder-green',
    featuresDescription: ['90s Video HUD [● REC, SP, BATTERY]', 'Tape Counter [0:24:18] & Date Time', 'Analog Video Scanlines & Noise', 'Hi8 Color Warmth'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'camcorder',
      presetId: 'camera-camcorder',
      exposure: 0.06,
      contrast: 0.14,
      temperature: 0.12,
      saturation: 0.15,
      vhsAmount: 0.4,
      prismAmount: 0.25,
      grainAmount: 0.22,
      glowAmount: 0.14,
    },
  },
  {
    id: 'handicam',
    name: 'handicam',
    subtitle: '2000s Digital Video Cam',
    tagline: '2000s Sony Handycam CCD aesthetic, crosshair focus brackets, STBY & zoom HUD',
    accentColor: '#0EA5E9',
    dateStampFormat: 'handicam-white',
    featuresDescription: ['2000s Handycam HUD [STBY, D.ZOOM 10x]', 'NightShot 0:14:02 & HQ 60i Status', 'Center Crosshair Focus Brackets [+]', 'CCD Sensor Clarity'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'handicam',
      presetId: 'camera-handicam',
      exposure: 0.08,
      contrast: 0.18,
      clarity: 0.2,
      temperature: -0.02,
      saturation: 0.16,
      vhsAmount: 0.2,
      prismAmount: 0.2,
      grainAmount: 0.14,
    },
  },
  {
    id: 'digiscan',
    name: 'digiscan',
    subtitle: 'CCD Flatbed Digiscan 700',
    tagline: 'Early CCD digital camera / flatbed scanner aesthetic, crisp pixelation texture',
    accentColor: '#64748B',
    dateStampFormat: 'none',
    featuresDescription: ['DIGISCAN CCD-700 • 3.2MP Stamp', 'Digital Grid Alignment Dots [+]', 'Early CCD Color Response', 'Crisp Sensor Clarity'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'digiscan',
      presetId: 'camera-digiscan',
      exposure: 0.06,
      contrast: 0.22,
      clarity: 0.3,
      temperature: -0.04,
      saturation: 0.14,
      grainAmount: 0.16,
      prismAmount: 0.2,
    },
  },
  {
    id: 'pinky',
    name: 'pinky',
    subtitle: 'Japanese Pastel Toy Cam',
    tagline: 'Soft candy pink tint, dreamy vignette, playful star and heart stamps',
    accentColor: '#F472B6',
    dateStampFormat: 'none',
    featuresDescription: ['PINKY POP ★ TOY CAM Stamp', 'Playful Star & Heart Marks [♥ ★]', 'Soft Candy Pink Tint', 'Dreamy Pastel Vignette'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'pinky',
      presetId: 'camera-pinky',
      exposure: 0.12,
      contrast: -0.06,
      highlights: -0.1,
      shadows: 0.24,
      temperature: 0.1,
      tint: 0.25,
      saturation: 0.12,
      vibrance: 0.24,
      glowAmount: 0.3,
      vignetteAmount: -0.15,
      grainAmount: 0.12,
    },
  },
  {
    id: 'lomo',
    name: 'lomo',
    subtitle: 'Lomography LC-A 32mm',
    tagline: 'Extreme heavy dark vignette, punchy cross-processed colors, wild contrast',
    accentColor: '#D97706',
    dateStampFormat: 'none',
    featuresDescription: ['LOMOGRAPHY LC-A 32mm Stamp', '"DON\'T THINK, JUST SHOOT!" Slogan', 'Heavy Signature Dark Vignette', 'Punchy Cross-Processed Colors'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'lomo',
      presetId: 'camera-lomo',
      exposure: 0.04,
      contrast: 0.35,
      highlights: -0.1,
      shadows: -0.1,
      saturation: 0.28,
      vibrance: 0.32,
      vignetteAmount: 0.55,
      vignetteRoundness: 0.7,
      grainAmount: 0.26,
      prismAmount: 0.25,
    },
  },
  {
    id: 'lumina',
    name: 'lumina',
    subtitle: 'High-Key Luminous Glow',
    tagline: 'High-key ethereal glow, diffused highlights, soft dreamy romantic lighting',
    accentColor: '#E2E8F0',
    dateStampFormat: 'none',
    featuresDescription: ['LUMINA HIGH-KEY • GLOW Emblem', 'Diffused White Highlight Blooming', 'Dreamy Romantic Pastel Lighting', 'Soft Ethereal Halo'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'lumina',
      presetId: 'camera-lumina',
      exposure: 0.16,
      contrast: -0.1,
      highlights: -0.05,
      shadows: 0.3,
      whites: 0.15,
      temperature: 0.08,
      saturation: -0.05,
      vibrance: 0.15,
      glowAmount: 0.45,
      glowRadius: 0.7,
      vignetteAmount: -0.2,
      grainAmount: 0.1,
    },
  },
  {
    id: 'ultragold',
    name: 'ultragold',
    subtitle: 'UltraGold 24K Luxe',
    tagline: 'Ultra-rich 24K golden tone, deep warm shadows, brass highlights, sunburst flare',
    accentColor: '#F59E0B',
    dateStampFormat: 'none',
    featuresDescription: ['ULTRAGOLD 24K • LUXE Crown Seal', 'Molten 24K Gold Highlights', 'Deep Warm Brass Shadows', 'Sunburst Flare Streak'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'ultragold',
      presetId: 'camera-ultragold',
      exposure: 0.06,
      contrast: 0.22,
      highlights: -0.2,
      shadows: 0.2,
      temperature: 0.42,
      tint: 0.08,
      saturation: 0.16,
      vibrance: 0.26,
      lightLeakType: 'sunset',
      lightLeakAmount: 0.35,
      glowAmount: 0.25,
      grainAmount: 0.18,
      vignetteAmount: 0.2,
    },
  },
  {
    id: 'retra',
    name: 'retra',
    subtitle: 'Retra 1974 Vintage Film',
    tagline: '70s faded sepia warmth, organic dust and scratches, aged paper warmth',
    accentColor: '#92400E',
    dateStampFormat: 'none',
    featuresDescription: ['RETRA 1974 • VINTAGE FILM Stamp', 'Aged 70s Sepia Warmth', 'Organic Dust Specks & Scratches', 'Faded Analog Film Gate'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'retra',
      presetId: 'camera-retra',
      exposure: 0.04,
      contrast: 0.1,
      highlights: -0.2,
      shadows: 0.22,
      blacks: 0.16,
      temperature: 0.32,
      tint: 0.1,
      saturation: -0.1,
      vibrance: 0.1,
      dustType: 'film-scratches',
      dustAmount: 0.35,
      grainAmount: 0.28,
      vignetteAmount: 0.25,
    },
  },
  {
    id: 'vhs',
    name: 'vhs',
    subtitle: 'Authentic VHS Tape SP',
    tagline: 'VHS HUD with PLAY ▶, SP 0:00:12, CH 03 and rainbow tracking noise line',
    accentColor: '#06B6D4',
    dateStampFormat: 'vhs-white',
    featuresDescription: ['Authentic VHS HUD [PLAY ▶, SP 0:00:12, CH 03]', 'Rainbow Chromatic Tracking Noise Line', 'Analog Tape Scanlines & Color Bleed', 'Retro Video Grain'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'vhs',
      presetId: 'camera-vhs',
      exposure: 0.05,
      contrast: 0.16,
      vhsAmount: 0.55,
      prismAmount: 0.35,
      grainAmount: 0.25,
      temperature: 0.1,
      saturation: 0.12,
    },
  },
  {
    id: 'tzachrome',
    name: 'tzachrome',
    subtitle: 'Tzachrome Slide 64',
    tagline: 'Kodachrome slide richness, deep saturated reds, authentic slide mount border',
    accentColor: '#B91C1C',
    dateStampFormat: 'none',
    featuresDescription: ['TZACHROME COLOR SLIDE • ISO 64 Stamp', 'Process K-14 Slide Mount Marking', 'Deep Saturated Reds & Rich Yellows', 'Slide Film Clarity'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'tzachrome',
      presetId: 'camera-tzachrome',
      frameType: 'slide-120',
      exposure: 0.02,
      contrast: 0.26,
      highlights: -0.16,
      shadows: 0.1,
      clarity: 0.22,
      temperature: 0.14,
      tint: 0.05,
      saturation: 0.22,
      vibrance: 0.26,
      grainAmount: 0.16,
      hsl: {
        ...defaultHSL,
        red: { hue: 0.02, saturation: 0.28, luminance: 0.04 },
        yellow: { hue: -0.08, saturation: 0.22, luminance: 0.06 },
      },
    },
  },
  {
    id: 'lofi',
    name: 'lofi',
    subtitle: 'Lo-Fi Cassette 90',
    tagline: 'Muted dusty palette, soft focus blur, cozy nostalgic bedroom warmth',
    accentColor: '#A16207',
    dateStampFormat: 'none',
    featuresDescription: ['LO-FI CASSETTE • 90 MIN Tape Stamp [◉ ◉]', 'STEREO CH A Indicator', 'Muted Dusty Pastel Palette', 'Soft Focus Nostalgic Glow'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'lofi',
      presetId: 'camera-lofi',
      exposure: 0.04,
      contrast: -0.06,
      highlights: -0.22,
      shadows: 0.26,
      blacks: 0.12,
      temperature: 0.2,
      tint: 0.06,
      saturation: -0.12,
      vibrance: 0.08,
      glowAmount: 0.25,
      grainAmount: 0.22,
      vignetteAmount: 0.2,
    },
  },
  {
    id: 'photobooth',
    name: 'photobooth',
    subtitle: 'NYC Vintage Photo Booth',
    tagline: 'Classic 4-pose photo booth flash contrast, authentic strip frame and stamp',
    accentColor: '#18181B',
    dateStampFormat: 'none',
    featuresDescription: ['PHOTO BOOTH • NYC Strip Stamp', '4 POSES • 25¢ Frame Counter [03 / 04]', 'High-Impact Direct Flash Contrast', 'Authentic Booth White Chin'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'photobooth',
      presetId: 'camera-photobooth',
      frameType: 'gallery-white',
      exposure: 0.08,
      contrast: 0.28,
      highlights: 0.06,
      shadows: -0.08,
      clarity: 0.2,
      grainAmount: 0.22,
      vignetteAmount: 0.25,
    },
  },
  {
    id: 'cinestil',
    name: 'cinestil',
    subtitle: 'CineStill 800T Tungsten',
    tagline: 'Iconic red halation bloom around highlights, cool teal shadows, moody cinema light',
    accentColor: '#EF4444',
    dateStampFormat: 'none',
    featuresDescription: ['CINESTILL 800T • TUNGSTEN Film Stamp', 'Iconic Intense Red Halation Glow', 'Moody Teal Shadows & Cyan Tint', 'Cinema 5219 Emulsion'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'cinestil',
      presetId: 'camera-cinestil',
      exposure: 0.04,
      contrast: 0.22,
      highlights: -0.14,
      shadows: 0.18,
      temperature: -0.22,
      tint: 0.08,
      saturation: 0.12,
      vibrance: 0.22,
      glowAmount: 0.45,
      glowRadius: 0.6,
      grainAmount: 0.22,
      grainSize: 1.1,
      vignetteAmount: 0.2,
      hsl: {
        ...defaultHSL,
        cyan: { hue: 0.08, saturation: 0.22, luminance: 0.02 },
        red: { hue: 0.06, saturation: 0.35, luminance: 0.1 },
        orange: { hue: -0.04, saturation: 0.25, luminance: 0.08 },
      },
    },
  },
  {
    id: '8mm',
    name: '8mm',
    subtitle: 'Vintage 1965 8mm Home Movie',
    tagline: 'Rounded 8mm gate border, organic jitter grain, sepia amber tone, movie frame',
    accentColor: '#78350F',
    dateStampFormat: 'none',
    featuresDescription: ['8MM HOME MOVIE • 1965 Rounded Gate', 'Side Film Sprocket Perforation', 'Organic Movie Jitter Grain', 'Kodachrome II Sepia Warmth'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: '8mm',
      presetId: 'camera-8mm',
      frameType: 'retro-tv',
      exposure: 0.06,
      contrast: 0.18,
      highlights: -0.2,
      shadows: 0.2,
      temperature: 0.34,
      tint: 0.08,
      saturation: -0.06,
      vibrance: 0.14,
      grainAmount: 0.35,
      grainSize: 1.4,
      dustType: 'film-scratches',
      dustAmount: 0.3,
      vignetteAmount: 0.3,
    },
  },
  {
    id: '16mm',
    name: '16mm',
    subtitle: '16mm Vision3 250D Cinema',
    tagline: 'Classic 16mm motion picture film with single perforation sprocket hole',
    accentColor: '#0284C7',
    dateStampFormat: 'none',
    featuresDescription: ['16MM KODAK VISION3 250D Edge Text', 'Single Perforation Sprocket Hole', 'EASTMAN 7207 Motion Picture Stamp', 'Rich Balanced Cinema Grain'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: '16mm',
      presetId: 'camera-16mm',
      frameType: 'film-35mm',
      exposure: 0.04,
      contrast: 0.18,
      highlights: -0.16,
      shadows: 0.14,
      temperature: 0.08,
      tint: 0.02,
      saturation: 0.12,
      vibrance: 0.2,
      grainAmount: 0.25,
      grainSize: 1.15,
      glowAmount: 0.15,
      vignetteAmount: 0.18,
    },
  },
  {
    id: 'super8',
    name: 'super8',
    subtitle: 'Super 8 Kodachrome 40',
    tagline: 'Super 8mm movie film look, rich warm colors, rounded Super 8 frame & sound stripe',
    accentColor: '#EA580C',
    dateStampFormat: 'none',
    featuresDescription: ['SUPER 8 KODACHROME 40 Stamp', 'Magnetic Sound Stripe & 18 FPS Badge', 'Rounded Super 8 Movie Gate', 'Rich Saturated Home Movie Colors'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'super8',
      presetId: 'camera-super8',
      frameType: 'retro-tv',
      exposure: 0.06,
      contrast: 0.22,
      highlights: -0.18,
      shadows: 0.16,
      temperature: 0.28,
      tint: 0.06,
      saturation: 0.2,
      vibrance: 0.24,
      grainAmount: 0.32,
      grainSize: 1.3,
      glowAmount: 0.2,
      vignetteAmount: 0.26,
    },
  },
  {
    id: 'super16',
    name: 'super16',
    subtitle: 'Super 16mm Cinema 500T',
    tagline: 'Modern widescreen 16:9 cinema crop with optical center crosshair & film gate marks',
    accentColor: '#0D9488',
    dateStampFormat: 'none',
    featuresDescription: ['SUPER 16MM CINEMA • 500T Frame Text', 'Center Optical Crosshair [+]', 'Widescreen 16:9 Cinema Crop', 'Fine Tungsten 500T Grain'],
    adjustments: {
      ...defaultAdjustments,
      cameraType: 'super16',
      presetId: 'camera-super16',
      cropAspect: '16:9',
      exposure: 0.04,
      contrast: 0.2,
      highlights: -0.15,
      shadows: 0.16,
      temperature: -0.06,
      tint: 0.02,
      saturation: 0.1,
      vibrance: 0.18,
      grainAmount: 0.2,
      grainSize: 1.0,
      glowAmount: 0.14,
      vignetteAmount: 0.2,
    },
  },
];

export const CAMERA_PROFILES_MAP: Record<CameraType, CameraProfile | undefined> = CAMERA_PROFILES.reduce(
  (acc, profile) => {
    acc[profile.id] = profile;
    return acc;
  },
  {} as Record<CameraType, CameraProfile | undefined>
);
