import { CollageTemplate } from '../types';
import { defaultAdjustments } from './defaultAdjustments';

export const COLLAGE_TEMPLATES: CollageTemplate[] = [
  // ==========================================
  // 1. AIRDROP REQUEST MODAL (Inspired by IMG_4059)
  // ==========================================
  {
    id: 'tpl-airdrop-modal',
    name: 'AirDrop Share Request',
    category: 'airdrop',
    categoryLabel: 'AirDrop Mockup',
    subtitle: 'Interactive iOS AirDrop dialog card over editorial photo',
    description: 'Customizable AirDrop modal popup over full background image/video with sender info, preview photo slot, and Decline/Accept action buttons.',
    aspectRatio: 9 / 16,
    aspectLabel: '9:16 Story',
    badge: 'Trending',
    previewThumbnail: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop',
    moodKeywords: ['AirDrop', 'iOS', 'Pop-up', 'Story', 'Interactive'],
    adjustments: {
      ...defaultAdjustments,
      presetId: 'inso',
      contrast: 0.1,
      temperature: 0.05,
      grainAmount: 0.15,
      vignetteAmount: 0.2,
    },
    overlays: {
      paperTexture: 'linen-white',
      backgroundColor: '#1E1D1B',
      airdropCard: {
        enabled: true,
        senderName: 'LumenLab Studio',
        deviceName: 'iPhone de Sophie',
        title: 'AirDrop',
        declineLabel: 'Refuser',
        acceptLabel: 'Accepter',
        accepted: false,
      },
    },
    slots: [
      {
        id: 'slot-airdrop-bg',
        label: 'Background Media',
        media: {
          id: 'media-airdrop-bg',
          name: 'Editorial Backdrop',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1200&auto=format&fit=crop',
          aspectRatio: 9 / 16,
          width: 1080,
          height: 1920,
        },
        x: 0,
        y: 0,
        width: 100,
        height: 100,
        fit: 'cover',
        borderStyle: 'none',
        shadow: 'none',
        zIndex: 1,
      },
      {
        id: 'slot-airdrop-preview',
        label: 'AirDrop Card Photo',
        media: {
          id: 'media-airdrop-item',
          name: 'AirDrop Featured Item',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1000&auto=format&fit=crop',
          aspectRatio: 1,
          width: 800,
          height: 800,
        },
        x: 18,
        y: 38,
        width: 64,
        height: 24,
        borderRadius: 14,
        fit: 'cover',
        borderStyle: 'none',
        shadow: 'subtle',
        zIndex: 10,
      },
    ],
    textElements: [
      {
        id: 'txt-airdrop-title',
        label: 'Header Title',
        text: 'AirDrop',
        fontFamily: 'modern-sans',
        fontSize: 16,
        color: '#FFFFFF',
        align: 'center',
        x: 50,
        y: 30.5,
        style: 'airdrop-title',
      },
      {
        id: 'txt-airdrop-subtitle',
        label: 'Device Subtitle',
        text: '“iPhone de Sophie” would like to share 1 photo.',
        fontFamily: 'modern-sans',
        fontSize: 11,
        color: '#E0E0E0',
        align: 'center',
        x: 50,
        y: 34,
      },
      {
        id: 'txt-airdrop-decline',
        label: 'Decline Button',
        text: 'Refuser',
        fontFamily: 'modern-sans',
        fontSize: 13,
        color: '#0A84FF',
        align: 'center',
        x: 32,
        y: 65.5,
      },
      {
        id: 'txt-airdrop-accept',
        label: 'Accept Button',
        text: 'Accepter',
        fontFamily: 'modern-sans',
        fontSize: 13,
        color: '#0A84FF',
        align: 'center',
        x: 68,
        y: 65.5,
      },
    ],
  },

  // ==========================================
  // 2. SPIRAL NOTEBOOK DUAL (Inspired by IMG_4065)
  // ==========================================
  {
    id: 'tpl-spiral-notebook',
    name: 'Spiral Sketchbook Dual',
    category: 'notebook',
    categoryLabel: 'Notebook & Binder',
    subtitle: 'Top & bottom split frames divided by realistic silver spiral rings',
    description: 'Dual photo/video split layout on textured sketch paper with chrome spiral notebook binding in the middle, and minimalist metadata notes.',
    aspectRatio: 9 / 16,
    aspectLabel: '9:16 Story',
    badge: 'Popular',
    previewThumbnail: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=800&auto=format&fit=crop',
    moodKeywords: ['Spiral', 'Sketchbook', 'Dual Frame', 'Journal', 'Editorial'],
    adjustments: {
      ...defaultAdjustments,
      presetId: 'vintage-film',
      temperature: 0.12,
      grainAmount: 0.22,
      contrast: 0.08,
    },
    overlays: {
      binderRings: 'middle-spiral',
      paperTexture: 'warm-ivory',
      backgroundColor: '#F5F2EB',
    },
    slots: [
      {
        id: 'slot-spiral-top',
        label: 'Top Photo / Video',
        media: {
          id: 'media-spiral-1',
          name: 'Editorial Look 1',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1000&auto=format&fit=crop',
          aspectRatio: 4 / 5,
          width: 900,
          height: 1125,
        },
        x: 8,
        y: 6,
        width: 84,
        height: 40,
        fit: 'cover',
        borderRadius: 4,
        shadow: 'subtle',
        zIndex: 2,
      },
      {
        id: 'slot-spiral-bottom',
        label: 'Bottom Photo / Video',
        media: {
          id: 'media-spiral-2',
          name: 'Editorial Look 2',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1000&auto=format&fit=crop',
          aspectRatio: 4 / 5,
          width: 900,
          height: 1125,
        },
        x: 8,
        y: 53,
        width: 84,
        height: 40,
        fit: 'cover',
        borderRadius: 4,
        shadow: 'subtle',
        zIndex: 2,
      },
    ],
    textElements: [
      {
        id: 'txt-spiral-header',
        label: 'Header Tag',
        text: 'VOL. 04 — DAILY REFLECTIONS',
        fontFamily: 'monospaced',
        fontSize: 10,
        color: '#7E7365',
        align: 'left',
        x: 8,
        y: 3.5,
        uppercase: true,
        letterSpacing: '0.15em',
      },
      {
        id: 'txt-spiral-footer',
        label: 'Bottom Note',
        text: 'SS25 COLLECTION • LUMENLAB STUDIO',
        fontFamily: 'monospaced',
        fontSize: 10,
        color: '#7E7365',
        align: 'right',
        x: 92,
        y: 95.5,
        uppercase: true,
        letterSpacing: '0.15em',
      },
    ],
  },

  // ==========================================
  // 3. TAPE & 35MM SCRAPBOOK (Inspired by IMG_4044)
  // ==========================================
  {
    id: 'tpl-tape-scrapbook',
    name: 'Tape & 35mm Scrapbook',
    category: 'scrapbook',
    categoryLabel: 'Washi & Tape',
    subtitle: '3 overlapping photos pinned with translucent washi tape & 35mm film',
    description: 'Scrapbook collage featuring a center 35mm sprocket film frame and two tilted photos attached with realistic translucent washi tape.',
    aspectRatio: 9 / 16,
    aspectLabel: '9:16 Story',
    badge: 'Aesthetic',
    previewThumbnail: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=800&auto=format&fit=crop',
    moodKeywords: ['Tape', 'Scrapbook', 'Washi', '35mm', 'Collage'],
    adjustments: {
      ...defaultAdjustments,
      presetId: 'vintage-gold',
      temperature: 0.15,
      contrast: 0.1,
      grainAmount: 0.25,
      dustAmount: 0.15,
    },
    overlays: {
      paperTexture: 'warm-ivory',
      backgroundColor: '#FAF7F0',
    },
    slots: [
      {
        id: 'slot-tape-left',
        label: 'Top-Left Photo',
        media: {
          id: 'media-tape-1',
          name: 'Detail Shot',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=800&auto=format&fit=crop',
          aspectRatio: 1,
          width: 700,
          height: 700,
        },
        x: 6,
        y: 8,
        width: 46,
        height: 30,
        rotation: -4,
        tape: 'top-corners',
        shadow: 'card',
        zIndex: 2,
      },
      {
        id: 'slot-tape-center',
        label: 'Center 35mm Film Hero',
        media: {
          id: 'media-tape-2',
          name: 'Hero Shot',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=1000&auto=format&fit=crop',
          aspectRatio: 4 / 5,
          width: 900,
          height: 1125,
        },
        x: 28,
        y: 28,
        width: 66,
        height: 44,
        rotation: 2,
        borderStyle: 'film-35mm',
        filmBorderText: 'TZ 1080 LINE SERIES • 400',
        shadow: 'deep',
        zIndex: 5,
      },
      {
        id: 'slot-tape-right',
        label: 'Bottom-Right Photo',
        media: {
          id: 'media-tape-3',
          name: 'Atmosphere Shot',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=800&auto=format&fit=crop',
          aspectRatio: 1,
          width: 700,
          height: 700,
        },
        x: 8,
        y: 65,
        width: 48,
        height: 28,
        rotation: -2,
        tape: 'diagonal-strip',
        shadow: 'card',
        zIndex: 3,
      },
    ],
    textElements: [
      {
        id: 'txt-tape-drop',
        label: 'Drop Label',
        text: 'NEW SPRING DROP (01)',
        fontFamily: 'typewriter',
        fontSize: 12,
        color: '#2A2723',
        align: 'left',
        x: 60,
        y: 80,
        style: 'typewriter-strip',
        rotation: -1,
      },
      {
        id: 'txt-tape-subtitle',
        label: 'Edition Note',
        text: 'LIMITED COLLECTION • SS25',
        fontFamily: 'monospaced',
        fontSize: 9,
        color: '#8A7F73',
        align: 'left',
        x: 60,
        y: 84.5,
      },
    ],
  },

  // ==========================================
  // 4. EDITORIAL BINDER DROP '25 (Inspired by IMG_4040, IMG_4041)
  // ==========================================
  {
    id: 'tpl-binder-editorial',
    name: 'Editorial Binder Drop 25',
    category: 'notebook',
    categoryLabel: 'Notebook & Binder',
    subtitle: 'Chrome 4-ring binder along side with modern lookbook typography',
    description: 'Lookbook page with metallic binder rings along the edge, hole punch cutouts, customizable hero photo/video slot, and high-fashion editorial manifesto.',
    aspectRatio: 4 / 5,
    aspectLabel: '4:5 Portrait',
    badge: 'Editorial',
    previewThumbnail: 'https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?q=80&w=800&auto=format&fit=crop',
    moodKeywords: ['Binder', 'Editorial', 'Lookbook', 'Minimal', 'Studio'],
    adjustments: {
      ...defaultAdjustments,
      presetId: 'editorial-clean',
      contrast: 0.12,
      clarity: 0.08,
      grainAmount: 0.1,
    },
    overlays: {
      binderRings: 'left-4ring',
      paperTexture: 'linen-white',
      backgroundColor: '#F8F6F0',
    },
    slots: [
      {
        id: 'slot-binder-hero',
        label: 'Lookbook Media Slot',
        media: {
          id: 'media-binder-1',
          name: 'Editorial Look',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?q=80&w=1000&auto=format&fit=crop',
          aspectRatio: 1,
          width: 900,
          height: 900,
        },
        x: 18,
        y: 20,
        width: 76,
        height: 52,
        fit: 'cover',
        borderRadius: 2,
        shadow: 'subtle',
        zIndex: 2,
      },
    ],
    textElements: [
      {
        id: 'txt-binder-header',
        label: 'Main Headline',
        text: "NEW COLLECTION '25 / LUMENLAB APP",
        fontFamily: 'display-syne',
        fontSize: 14,
        color: '#2A2723',
        align: 'left',
        x: 18,
        y: 11,
        uppercase: true,
        letterSpacing: '0.08em',
      },
      {
        id: 'txt-binder-quote',
        label: 'Lookbook Paragraph',
        text: 'A visual identity is not merely what you observe — it is an uncompromising statement of authentic artistry and mood.',
        fontFamily: 'editorial-serif',
        fontSize: 12,
        color: '#5C5449',
        align: 'left',
        x: 18,
        y: 77,
        width: 76,
      },
      {
        id: 'txt-binder-metadata',
        label: 'Footer Metadata',
        text: 'ISSUE NO. 08 • GLOBAL EDITION',
        fontFamily: 'monospaced',
        fontSize: 9,
        color: '#9C9082',
        align: 'left',
        x: 18,
        y: 91,
      },
    ],
  },

  // ==========================================
  // 5. WASHI SALE LOOKBOOK (Inspired by IMG_4056)
  // ==========================================
  {
    id: 'tpl-washi-sale',
    name: 'Washi Sale Lookbook',
    category: 'scrapbook',
    categoryLabel: 'Washi & Tape',
    subtitle: 'Corner metallic paperclip pinning a typewriter promotional memo card',
    description: 'Full-bleed portrait photo slot with a realistic metallic paperclip in the top corner holding an ivory sale notice card.',
    aspectRatio: 9 / 16,
    aspectLabel: '9:16 Story',
    badge: 'Sale / Drop',
    previewThumbnail: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?q=80&w=800&auto=format&fit=crop',
    moodKeywords: ['Sale', 'Paperclip', 'Promo', 'Typewriter', 'Story'],
    adjustments: {
      ...defaultAdjustments,
      presetId: 'sunbath-warm',
      temperature: 0.18,
      contrast: 0.1,
      grainAmount: 0.2,
    },
    overlays: {
      paperTexture: 'clean-white',
      backgroundColor: '#FAF9F6',
    },
    slots: [
      {
        id: 'slot-sale-bg',
        label: 'Hero Photo / Video',
        media: {
          id: 'media-sale-1',
          name: 'Hero Fashion Shoot',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?q=80&w=1080&auto=format&fit=crop',
          aspectRatio: 9 / 16,
          width: 1080,
          height: 1920,
        },
        x: 5,
        y: 5,
        width: 90,
        height: 90,
        fit: 'cover',
        borderRadius: 4,
        paperClip: 'top-left',
        shadow: 'card',
        zIndex: 2,
      },
    ],
    textElements: [
      {
        id: 'txt-sale-card',
        label: 'Sale Memo Card',
        text: 'Limited time only — exclusive seasonal sale!\nUp to 70% off on selected styles.',
        fontFamily: 'typewriter',
        fontSize: 12,
        color: '#2A2723',
        align: 'left',
        x: 12,
        y: 12,
        width: 76,
        style: 'memo-card',
        rotation: -1,
      },
      {
        id: 'txt-sale-cta',
        label: 'Bottom Swipe CTA',
        text: 'SHOP NOW • LUMENLAB.COM',
        fontFamily: 'monospaced',
        fontSize: 10,
        color: '#FFFFFF',
        align: 'center',
        x: 50,
        y: 88,
        uppercase: true,
        letterSpacing: '0.2em',
      },
    ],
  },

  // ==========================================
  // 6. DUAL POLAROID STACKS (Inspired by IMG_4051, IMG_4066)
  // ==========================================
  {
    id: 'tpl-polaroid-dual',
    name: 'Dual Polaroid Stacks',
    category: 'polaroid-stack',
    categoryLabel: 'Polaroid & Film',
    subtitle: 'Two offset instant photos with realistic white frames & soft shadows',
    description: 'Two tilted instant Polaroid prints overlapping on a subtle warm duotone backdrop with handwritten date captions.',
    aspectRatio: 9 / 16,
    aspectLabel: '9:16 Story',
    previewThumbnail: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop',
    moodKeywords: ['Polaroid', 'Dual', 'Instant', 'Nostalgic', 'Summer'],
    adjustments: {
      ...defaultAdjustments,
      presetId: 'vintage-film',
      temperature: 0.14,
      grainAmount: 0.24,
      dustAmount: 0.1,
    },
    overlays: {
      paperTexture: 'split-duotone',
      backgroundColor: '#F3EFE6',
    },
    slots: [
      {
        id: 'slot-polaroid-top',
        label: 'Top Polaroid',
        media: {
          id: 'media-pol-1',
          name: 'Summer Memory 1',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=900&auto=format&fit=crop',
          aspectRatio: 1,
          width: 800,
          height: 800,
        },
        x: 10,
        y: 10,
        width: 74,
        height: 42,
        rotation: -4,
        borderStyle: 'polaroid',
        shadow: 'polaroid-deep',
        tape: 'top-center',
        zIndex: 2,
      },
      {
        id: 'slot-polaroid-bottom',
        label: 'Bottom Polaroid',
        media: {
          id: 'media-pol-2',
          name: 'Summer Memory 2',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=900&auto=format&fit=crop',
          aspectRatio: 1,
          width: 800,
          height: 800,
        },
        x: 16,
        y: 48,
        width: 74,
        height: 42,
        rotation: 3,
        borderStyle: 'polaroid',
        shadow: 'polaroid-deep',
        tape: 'diagonal-strip',
        zIndex: 4,
      },
    ],
    textElements: [
      {
        id: 'txt-pol-caption',
        label: 'Handwritten Caption',
        text: 'golden hour in the city // 1998',
        fontFamily: 'handwritten',
        fontSize: 18,
        color: '#423B32',
        align: 'center',
        x: 50,
        y: 93,
      },
    ],
  },

  // ==========================================
  // 7. DOUBLE 35MM FILM REEL (Inspired by IMG_4037)
  // ==========================================
  {
    id: 'tpl-film-reel-double',
    name: 'Double 35mm Film Reel',
    category: 'film-strip',
    categoryLabel: 'Film & Sprockets',
    subtitle: 'Vertical cinema strip with authentic sprocket holes & frame numbers',
    description: 'Two vertical 35mm film frames in sequence with authentic analog sprocket notches, frame numbers 01 & 02, and film brand stamps.',
    aspectRatio: 9 / 16,
    aspectLabel: '9:16 Story',
    previewThumbnail: 'https://images.unsplash.com/photo-1488161628813-04466f872be2?q=80&w=800&auto=format&fit=crop',
    moodKeywords: ['35mm', 'Reel', 'Film Strip', 'Cinema', 'Retro'],
    adjustments: {
      ...defaultAdjustments,
      presetId: 'kodak-gold',
      temperature: 0.16,
      grainAmount: 0.3,
      contrast: 0.14,
    },
    overlays: {
      paperTexture: 'charcoal-dark',
      backgroundColor: '#141416',
    },
    slots: [
      {
        id: 'slot-reel-1',
        label: 'Film Frame 01',
        media: {
          id: 'media-reel-1',
          name: 'Scene 01',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1488161628813-04466f872be2?q=80&w=900&auto=format&fit=crop',
          aspectRatio: 4 / 5,
          width: 800,
          height: 1000,
        },
        x: 12,
        y: 6,
        width: 76,
        height: 42,
        borderStyle: 'film-35mm',
        filmBorderText: 'LUMENLAB 35MM • 01',
        shadow: 'card',
        zIndex: 2,
      },
      {
        id: 'slot-reel-2',
        label: 'Film Frame 02',
        media: {
          id: 'media-reel-2',
          name: 'Scene 02',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=900&auto=format&fit=crop',
          aspectRatio: 4 / 5,
          width: 800,
          height: 1000,
        },
        x: 12,
        y: 52,
        width: 76,
        height: 42,
        borderStyle: 'film-35mm',
        filmBorderText: 'LUMENLAB 35MM • 02',
        shadow: 'card',
        zIndex: 2,
      },
    ],
    textElements: [
      {
        id: 'txt-reel-stamp',
        label: 'Film Stamp Top',
        text: '▶ 35MM KODAK PORTRA 400 EXP',
        fontFamily: 'monospaced',
        fontSize: 9,
        color: '#E5A93C',
        align: 'left',
        x: 14,
        y: 3.5,
      },
    ],
  },

  // ==========================================
  // 8. THE ART OF SELF EXPRESSION (Inspired by IMG_4055)
  // ==========================================
  {
    id: 'tpl-art-expression',
    name: 'The Art of Self Expression',
    category: 'handwritten-story',
    categoryLabel: 'Handwritten & Script',
    subtitle: 'Signature handwritten cursive title overlay & manifesto paragraph',
    description: 'Full-screen editorial story with elegant authentic white cursive title "the art of self expression" and lower modern editorial manifesto text.',
    aspectRatio: 9 / 16,
    aspectLabel: '9:16 Story',
    badge: 'Signature',
    previewThumbnail: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=800&auto=format&fit=crop',
    moodKeywords: ['Handwritten', 'Script', 'Self Expression', 'Luxury', 'Story'],
    adjustments: {
      ...defaultAdjustments,
      presetId: 'editorial-moody',
      contrast: 0.15,
      temperature: -0.05,
      grainAmount: 0.18,
      vignetteAmount: 0.25,
    },
    overlays: {
      paperTexture: 'none',
      backgroundColor: '#121214',
    },
    slots: [
      {
        id: 'slot-expression-bg',
        label: 'Hero Photo / Video',
        media: {
          id: 'media-expr-1',
          name: 'Cinematic Portrait',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=1080&auto=format&fit=crop',
          aspectRatio: 9 / 16,
          width: 1080,
          height: 1920,
        },
        x: 0,
        y: 0,
        width: 100,
        height: 100,
        fit: 'cover',
        borderStyle: 'none',
        shadow: 'none',
        zIndex: 1,
      },
    ],
    textElements: [
      {
        id: 'txt-expr-title',
        label: 'Handwritten Title',
        text: 'the art of self expression',
        fontFamily: 'handwritten',
        fontSize: 34,
        color: '#FFFFFF',
        align: 'center',
        x: 50,
        y: 22,
        rotation: -3,
      },
      {
        id: 'txt-expr-manifesto',
        label: 'Manifesto Body',
        text: 'Style is an instinctive dialogue between light, texture, and silence. When you wear what reflects your soul, you create art without speaking.',
        fontFamily: 'editorial-serif',
        fontSize: 13,
        color: '#F0ECE1',
        align: 'center',
        x: 50,
        y: 78,
        width: 82,
      },
      {
        id: 'txt-expr-credit',
        label: 'Editorial Credit',
        text: 'LUMENLAB EDITORIAL • NEW YORK',
        fontFamily: 'monospaced',
        fontSize: 9,
        color: '#D4CEBF',
        align: 'center',
        x: 50,
        y: 89,
        letterSpacing: '0.2em',
      },
    ],
  },

  // ==========================================
  // 9. DOODLE ARROW MOODBOARD (Inspired by IMG_4062)
  // ==========================================
  {
    id: 'tpl-doodle-moodboard',
    name: 'Doodle Arrow Moodboard',
    category: 'scrapbook',
    categoryLabel: 'Washi & Tape',
    subtitle: '4 collage slots with sketched pencil circle doodles & hand-drawn arrow',
    description: 'Creative lookbook collage with 4 overlapping photos, torn paper notes, hand-drawn pencil circle doodle highlighting "new collection drop", and sketch arrow.',
    aspectRatio: 9 / 16,
    aspectLabel: '9:16 Story',
    previewThumbnail: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop',
    moodKeywords: ['Doodle', 'Moodboard', 'Arrow', 'Sketch', 'Collage'],
    adjustments: {
      ...defaultAdjustments,
      presetId: 'vintage-gold',
      temperature: 0.12,
      grainAmount: 0.22,
    },
    overlays: {
      paperTexture: 'linen-white',
      backgroundColor: '#FAF8F5',
      doodles: [
        {
          id: 'doodle-1',
          type: 'circle-arrow',
          x: 50,
          y: 46,
          label: 'new collection drop',
          color: '#2A2723',
        },
      ],
    },
    slots: [
      {
        id: 'slot-mood-1',
        label: 'Top-Left Photo',
        media: {
          id: 'media-mood-1',
          name: 'Mood 1',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop',
          aspectRatio: 1,
          width: 700,
          height: 700,
        },
        x: 8,
        y: 8,
        width: 44,
        height: 28,
        rotation: -3,
        tape: 'top-corners',
        shadow: 'card',
        zIndex: 2,
      },
      {
        id: 'slot-mood-2',
        label: 'Top-Right Photo',
        media: {
          id: 'media-mood-2',
          name: 'Mood 2',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop',
          aspectRatio: 1,
          width: 700,
          height: 700,
        },
        x: 48,
        y: 14,
        width: 44,
        height: 30,
        rotation: 4,
        paperClip: 'top-right',
        shadow: 'card',
        zIndex: 3,
      },
      {
        id: 'slot-mood-3',
        label: 'Bottom Hero Photo',
        media: {
          id: 'media-mood-3',
          name: 'Hero Focus',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=900&auto=format&fit=crop',
          aspectRatio: 4 / 5,
          width: 800,
          height: 1000,
        },
        x: 20,
        y: 48,
        width: 62,
        height: 42,
        rotation: -1,
        borderStyle: 'polaroid',
        shadow: 'polaroid-deep',
        zIndex: 5,
      },
    ],
    textElements: [
      {
        id: 'txt-mood-doodle-label',
        label: 'Handwritten Note',
        text: '✦ new collection drop ✦',
        fontFamily: 'handwritten',
        fontSize: 18,
        color: '#D9534F',
        align: 'center',
        x: 50,
        y: 44,
        rotation: -4,
      },
    ],
  },

  // ==========================================
  // 10. 6-PACK POLAROID CONTACT (Inspired by IMG_4057)
  // ==========================================
  {
    id: 'tpl-polaroid-6pack',
    name: '6-Pack Polaroid Contact Sheet',
    category: 'polaroid-stack',
    categoryLabel: 'Polaroid & Film',
    subtitle: '2 columns x 3 rows of 6 customizable Polaroid instant prints',
    description: 'Grid of 6 mini Polaroid instant prints on vintage textured linen, perfect for multi-look recap, travel diaries, or outfit collections.',
    aspectRatio: 9 / 16,
    aspectLabel: '9:16 Story',
    previewThumbnail: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=800&auto=format&fit=crop',
    moodKeywords: ['6-Pack', 'Polaroid', 'Grid', 'Contact Sheet', 'Recap'],
    adjustments: {
      ...defaultAdjustments,
      presetId: 'vintage-film',
      temperature: 0.1,
      grainAmount: 0.2,
    },
    overlays: {
      paperTexture: 'warm-ivory',
      backgroundColor: '#F3EFE6',
    },
    slots: [
      {
        id: 'slot-6p-1',
        label: 'Photo 1',
        media: {
          id: 'media-6p-1',
          name: 'Frame 1',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=600&auto=format&fit=crop',
          aspectRatio: 1,
          width: 500,
          height: 500,
        },
        x: 6,
        y: 6,
        width: 42,
        height: 27,
        borderStyle: 'polaroid',
        shadow: 'subtle',
        zIndex: 2,
      },
      {
        id: 'slot-6p-2',
        label: 'Photo 2',
        media: {
          id: 'media-6p-2',
          name: 'Frame 2',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=600&auto=format&fit=crop',
          aspectRatio: 1,
          width: 500,
          height: 500,
        },
        x: 52,
        y: 6,
        width: 42,
        height: 27,
        borderStyle: 'polaroid',
        shadow: 'subtle',
        zIndex: 2,
      },
      {
        id: 'slot-6p-3',
        label: 'Photo 3',
        media: {
          id: 'media-6p-3',
          name: 'Frame 3',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=600&auto=format&fit=crop',
          aspectRatio: 1,
          width: 500,
          height: 500,
        },
        x: 6,
        y: 36,
        width: 42,
        height: 27,
        borderStyle: 'polaroid',
        shadow: 'subtle',
        zIndex: 2,
      },
      {
        id: 'slot-6p-4',
        label: 'Photo 4',
        media: {
          id: 'media-6p-4',
          name: 'Frame 4',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop',
          aspectRatio: 1,
          width: 500,
          height: 500,
        },
        x: 52,
        y: 36,
        width: 42,
        height: 27,
        borderStyle: 'polaroid',
        shadow: 'subtle',
        zIndex: 2,
      },
      {
        id: 'slot-6p-5',
        label: 'Photo 5',
        media: {
          id: 'media-6p-5',
          name: 'Frame 5',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=600&auto=format&fit=crop',
          aspectRatio: 1,
          width: 500,
          height: 500,
        },
        x: 6,
        y: 66,
        width: 42,
        height: 27,
        borderStyle: 'polaroid',
        shadow: 'subtle',
        zIndex: 2,
      },
      {
        id: 'slot-6p-6',
        label: 'Photo 6',
        media: {
          id: 'media-6p-6',
          name: 'Frame 6',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?q=80&w=600&auto=format&fit=crop',
          aspectRatio: 1,
          width: 500,
          height: 500,
        },
        x: 52,
        y: 66,
        width: 42,
        height: 27,
        borderStyle: 'polaroid',
        shadow: 'subtle',
        zIndex: 2,
      },
    ],
    textElements: [
      {
        id: 'txt-6p-footer',
        label: 'Bottom Tag',
        text: 'POLAROID ARCHIVE // RECAP SS25',
        fontFamily: 'monospaced',
        fontSize: 9,
        color: '#7A7063',
        align: 'center',
        x: 50,
        y: 96,
        letterSpacing: '0.15em',
      },
    ],
  },

  // ==========================================
  // 11. EDITORIAL BENTO MAGAZINE (Inspired by IMG_4042, IMG_4038)
  // ==========================================
  {
    id: 'tpl-editorial-bento',
    name: 'Editorial Bento Magazine',
    category: 'editorial-grid',
    categoryLabel: 'Editorial & Bento',
    subtitle: '1 large hero portrait + 3 stacked right thumbnails + bottom frame',
    description: 'Asymmetric 5-slot editorial lookbook bento grid combining a tall hero vertical photo with three stacked right thumbnails and a wide bottom frame.',
    aspectRatio: 9 / 16,
    aspectLabel: '9:16 Story',
    badge: 'Bento',
    previewThumbnail: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=800&auto=format&fit=crop',
    moodKeywords: ['Bento', 'Editorial', 'Magazine', 'Grid', 'Multi-Slot'],
    adjustments: {
      ...defaultAdjustments,
      presetId: 'editorial-clean',
      contrast: 0.1,
      clarity: 0.08,
    },
    overlays: {
      paperTexture: 'linen-white',
      backgroundColor: '#FAF8F5',
    },
    slots: [
      {
        id: 'slot-bento-hero',
        label: 'Main Hero Portrait',
        media: {
          id: 'media-bento-1',
          name: 'Hero Look',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=900&auto=format&fit=crop',
          aspectRatio: 3 / 4,
          width: 800,
          height: 1060,
        },
        x: 6,
        y: 6,
        width: 58,
        height: 60,
        fit: 'cover',
        borderRadius: 4,
        shadow: 'subtle',
        zIndex: 2,
      },
      {
        id: 'slot-bento-thumb1',
        label: 'Right Thumbnail 1',
        media: {
          id: 'media-bento-2',
          name: 'Detail 1',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=600&auto=format&fit=crop',
          aspectRatio: 1,
          width: 500,
          height: 500,
        },
        x: 67,
        y: 6,
        width: 27,
        height: 18.5,
        fit: 'cover',
        borderRadius: 4,
        shadow: 'subtle',
        zIndex: 2,
      },
      {
        id: 'slot-bento-thumb2',
        label: 'Right Thumbnail 2',
        media: {
          id: 'media-bento-3',
          name: 'Detail 2',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop',
          aspectRatio: 1,
          width: 500,
          height: 500,
        },
        x: 67,
        y: 26.8,
        width: 27,
        height: 18.5,
        fit: 'cover',
        borderRadius: 4,
        shadow: 'subtle',
        zIndex: 2,
      },
      {
        id: 'slot-bento-thumb3',
        label: 'Right Thumbnail 3',
        media: {
          id: 'media-bento-4',
          name: 'Detail 3',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=600&auto=format&fit=crop',
          aspectRatio: 1,
          width: 500,
          height: 500,
        },
        x: 67,
        y: 47.5,
        width: 27,
        height: 18.5,
        fit: 'cover',
        borderRadius: 4,
        shadow: 'subtle',
        zIndex: 2,
      },
      {
        id: 'slot-bento-bottom',
        label: 'Bottom Wide Frame',
        media: {
          id: 'media-bento-5',
          name: 'Bottom Landscape',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=900&auto=format&fit=crop',
          aspectRatio: 16 / 9,
          width: 1000,
          height: 560,
        },
        x: 6,
        y: 69,
        width: 88,
        height: 24,
        fit: 'cover',
        borderRadius: 4,
        shadow: 'subtle',
        zIndex: 2,
      },
    ],
    textElements: [
      {
        id: 'txt-bento-title',
        label: 'Editorial Tag',
        text: 'LOOKBOOK 2025 // ISSUE 01',
        fontFamily: 'display-syne',
        fontSize: 10,
        color: '#2A2723',
        align: 'left',
        x: 6,
        y: 95.5,
        letterSpacing: '0.15em',
      },
    ],
  },

  // ==========================================
  // 12. 9-GRID INSTAGRAM LOOKBOOK (Inspired by IMG_4061)
  // ==========================================
  {
    id: 'tpl-9grid-instagram',
    name: '9-Grid Instagram Lookbook',
    category: 'editorial-grid',
    categoryLabel: 'Editorial & Bento',
    subtitle: '3x3 photo grid layout with interactive like hearts & clean spacing',
    description: 'Classic 3x3 grid aesthetic with subtle gaps, interactive like hearts on photos, and support for 9 custom images/videos.',
    aspectRatio: 1,
    aspectLabel: '1:1 Square',
    previewThumbnail: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop',
    moodKeywords: ['9-Grid', 'Instagram', 'Feed', 'Grid', 'Square'],
    adjustments: {
      ...defaultAdjustments,
      presetId: 'clean-crisp',
      contrast: 0.08,
      temperature: 0.04,
    },
    overlays: {
      paperTexture: 'clean-white',
      backgroundColor: '#FFFFFF',
    },
    slots: [
      {
        id: 'slot-9g-1',
        label: 'Grid 1',
        media: {
          id: 'm-9g-1',
          name: 'G1',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop',
          aspectRatio: 1,
          width: 500,
          height: 500,
        },
        x: 2,
        y: 2,
        width: 30.6,
        height: 30.6,
        heartBadge: true,
        likeCount: '1.4k',
      },
      {
        id: 'slot-9g-2',
        label: 'Grid 2',
        media: {
          id: 'm-9g-2',
          name: 'G2',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=600&auto=format&fit=crop',
          aspectRatio: 1,
          width: 500,
          height: 500,
        },
        x: 34.6,
        y: 2,
        width: 30.6,
        height: 30.6,
      },
      {
        id: 'slot-9g-3',
        label: 'Grid 3',
        media: {
          id: 'm-9g-3',
          name: 'G3',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=600&auto=format&fit=crop',
          aspectRatio: 1,
          width: 500,
          height: 500,
        },
        x: 67.2,
        y: 2,
        width: 30.6,
        height: 30.6,
      },
      {
        id: 'slot-9g-4',
        label: 'Grid 4',
        media: {
          id: 'm-9g-4',
          name: 'G4',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=600&auto=format&fit=crop',
          aspectRatio: 1,
          width: 500,
          height: 500,
        },
        x: 2,
        y: 34.6,
        width: 30.6,
        height: 30.6,
      },
      {
        id: 'slot-9g-5',
        label: 'Grid 5',
        media: {
          id: 'm-9g-5',
          name: 'G5',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=600&auto=format&fit=crop',
          aspectRatio: 1,
          width: 500,
          height: 500,
        },
        x: 34.6,
        y: 34.6,
        width: 30.6,
        height: 30.6,
        heartBadge: true,
        likeCount: '3.2k',
      },
      {
        id: 'slot-9g-6',
        label: 'Grid 6',
        media: {
          id: 'm-9g-6',
          name: 'G6',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=600&auto=format&fit=crop',
          aspectRatio: 1,
          width: 500,
          height: 500,
        },
        x: 67.2,
        y: 34.6,
        width: 30.6,
        height: 30.6,
      },
      {
        id: 'slot-9g-7',
        label: 'Grid 7',
        media: {
          id: 'm-9g-7',
          name: 'G7',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?q=80&w=600&auto=format&fit=crop',
          aspectRatio: 1,
          width: 500,
          height: 500,
        },
        x: 2,
        y: 67.2,
        width: 30.6,
        height: 30.6,
      },
      {
        id: 'slot-9g-8',
        label: 'Grid 8',
        media: {
          id: 'm-9g-8',
          name: 'G8',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=600&auto=format&fit=crop',
          aspectRatio: 1,
          width: 500,
          height: 500,
        },
        x: 34.6,
        y: 67.2,
        width: 30.6,
        height: 30.6,
      },
      {
        id: 'slot-9g-9',
        label: 'Grid 9',
        media: {
          id: 'm-9g-9',
          name: 'G9',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=600&auto=format&fit=crop',
          aspectRatio: 1,
          width: 500,
          height: 500,
        },
        x: 67.2,
        y: 67.2,
        width: 30.6,
        height: 30.6,
        heartBadge: true,
        likeCount: '890',
      },
    ],
    textElements: [],
  },

  // ==========================================
  // 13. TAPED POLAROID NYC (Inspired by IMG_4047)
  // ==========================================
  {
    id: 'tpl-taped-polaroid-nyc',
    name: 'Taped Polaroid NYC',
    category: 'scrapbook',
    categoryLabel: 'Washi & Tape',
    subtitle: '4 scotch tape pieces on corners with handwritten "New Collection MADE IN NYC"',
    description: 'Large central Polaroid instant frame pinned with scotch tape on all 4 corners and stylish handwritten cursive text overlay.',
    aspectRatio: 9 / 16,
    aspectLabel: '9:16 Story',
    previewThumbnail: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=800&auto=format&fit=crop',
    moodKeywords: ['Tape', 'Polaroid', 'NYC', 'Handwritten', 'Story'],
    adjustments: {
      ...defaultAdjustments,
      presetId: 'vintage-film',
      temperature: 0.15,
      grainAmount: 0.22,
    },
    overlays: {
      paperTexture: 'warm-ivory',
      backgroundColor: '#FAF7F0',
    },
    slots: [
      {
        id: 'slot-nyc-polaroid',
        label: 'Hero Polaroid',
        media: {
          id: 'media-nyc-1',
          name: 'NYC Collection',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=1000&auto=format&fit=crop',
          aspectRatio: 4 / 5,
          width: 900,
          height: 1125,
        },
        x: 10,
        y: 14,
        width: 80,
        height: 68,
        borderStyle: 'polaroid',
        tape: 'all-corners',
        shadow: 'polaroid-deep',
        zIndex: 2,
      },
    ],
    textElements: [
      {
        id: 'txt-nyc-script',
        label: 'Handwritten Script Title',
        text: 'New Collection',
        fontFamily: 'handwritten',
        fontSize: 32,
        color: '#FFFFFF',
        align: 'center',
        x: 50,
        y: 42,
        rotation: -4,
      },
      {
        id: 'txt-nyc-caps',
        label: 'Caps Subtitle',
        text: 'MADE IN NYC • SS25',
        fontFamily: 'display-syne',
        fontSize: 12,
        color: '#FFFFFF',
        align: 'center',
        x: 50,
        y: 49,
        letterSpacing: '0.2em',
      },
      {
        id: 'txt-nyc-footer',
        label: 'Bottom Tag',
        text: 'EXCLUSIVE DROP // @LUMENLAB',
        fontFamily: 'monospaced',
        fontSize: 9,
        color: '#7A7063',
        align: 'center',
        x: 50,
        y: 91,
      },
    ],
  },

  // ==========================================
  // 14. TRIPLE FILM CONTACT STRIP (Inspired by IMG_4043)
  // ==========================================
  {
    id: 'tpl-triple-film-strip',
    name: 'Triple Film Contact Strip',
    category: 'film-strip',
    categoryLabel: 'Film & Sprockets',
    subtitle: '1 top wide hero photo + 3 bottom vertical 35mm film frames',
    description: 'Contact sheet layout with a panoramic 16:9 top frame and three vertical 35mm film frames side-by-side at the bottom.',
    aspectRatio: 9 / 16,
    aspectLabel: '9:16 Story',
    previewThumbnail: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=800&auto=format&fit=crop',
    moodKeywords: ['35mm', 'Triple', 'Film Strip', 'Contact Sheet', 'Cinema'],
    adjustments: {
      ...defaultAdjustments,
      presetId: 'vintage-film',
      temperature: 0.12,
      grainAmount: 0.25,
      dustAmount: 0.1,
    },
    overlays: {
      paperTexture: 'linen-white',
      backgroundColor: '#FAF8F5',
    },
    slots: [
      {
        id: 'slot-trip-top',
        label: 'Top Wide Hero',
        media: {
          id: 'media-trip-1',
          name: 'Wide Hero',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=1000&auto=format&fit=crop',
          aspectRatio: 16 / 9,
          width: 1000,
          height: 560,
        },
        x: 6,
        y: 6,
        width: 88,
        height: 40,
        fit: 'cover',
        borderRadius: 4,
        shadow: 'card',
        zIndex: 2,
      },
      {
        id: 'slot-trip-b1',
        label: 'Bottom Frame 1',
        media: {
          id: 'media-trip-2',
          name: 'Reel A',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=600&auto=format&fit=crop',
          aspectRatio: 9 / 16,
          width: 500,
          height: 880,
        },
        x: 6,
        y: 50,
        width: 27,
        height: 42,
        borderStyle: 'film-35mm',
        filmBorderText: '35MM • 01',
        shadow: 'subtle',
        zIndex: 2,
      },
      {
        id: 'slot-trip-b2',
        label: 'Bottom Frame 2',
        media: {
          id: 'media-trip-3',
          name: 'Reel B',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop',
          aspectRatio: 9 / 16,
          width: 500,
          height: 880,
        },
        x: 36.5,
        y: 50,
        width: 27,
        height: 42,
        borderStyle: 'film-35mm',
        filmBorderText: '35MM • 02',
        shadow: 'subtle',
        zIndex: 2,
      },
      {
        id: 'slot-trip-b3',
        label: 'Bottom Frame 3',
        media: {
          id: 'media-trip-4',
          name: 'Reel C',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=600&auto=format&fit=crop',
          aspectRatio: 9 / 16,
          width: 500,
          height: 880,
        },
        x: 67,
        y: 50,
        width: 27,
        height: 42,
        borderStyle: 'film-35mm',
        filmBorderText: '35MM • 03',
        shadow: 'subtle',
        zIndex: 2,
      },
    ],
    textElements: [
      {
        id: 'txt-trip-header',
        label: 'Film Contact Note',
        text: 'FILM CONTACT SHEET // EXP 400',
        fontFamily: 'monospaced',
        fontSize: 9,
        color: '#7E7365',
        align: 'center',
        x: 50,
        y: 95.5,
      },
    ],
  },

  // ==========================================
  // 15. BOOKMARK SALE STRIP (Inspired by IMG_4052)
  // ==========================================
  {
    id: 'tpl-bookmark-sale',
    name: 'Bookmark Sale Strip',
    category: 'scrapbook',
    categoryLabel: 'Washi & Tape',
    subtitle: 'Vertical paper bookmark with paperclips at top & bottom over photo',
    description: 'Full-bleed photo slot with a centered vertical paper bookmark pinned with metallic clips displaying typewriter seasonal discount information.',
    aspectRatio: 9 / 16,
    aspectLabel: '9:16 Story',
    previewThumbnail: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop',
    moodKeywords: ['Bookmark', 'Sale', 'Paperclip', 'Editorial', 'Story'],
    adjustments: {
      ...defaultAdjustments,
      presetId: 'sunbath-warm',
      temperature: 0.16,
      grainAmount: 0.18,
    },
    overlays: {
      paperTexture: 'none',
      backgroundColor: '#1E1D1A',
    },
    slots: [
      {
        id: 'slot-bm-bg',
        label: 'Background Photo / Video',
        media: {
          id: 'media-bm-1',
          name: 'Hero Shot',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1080&auto=format&fit=crop',
          aspectRatio: 9 / 16,
          width: 1080,
          height: 1920,
        },
        x: 0,
        y: 0,
        width: 100,
        height: 100,
        fit: 'cover',
        zIndex: 1,
      },
    ],
    textElements: [
      {
        id: 'txt-bm-body',
        label: 'Bookmark Typewriter Text',
        text: 'Exclusive seasonal sale!\nUp to 70% off on selected styles.\n\nLimited time only.\nValid online & in studio.',
        fontFamily: 'typewriter',
        fontSize: 13,
        color: '#2A2723',
        align: 'center',
        x: 50,
        y: 40,
        width: 68,
        style: 'memo-card',
      },
    ],
  },

  // ==========================================
  // 16. 4-SLOT QUAD 2X2 COLLAGE (Mix Photos & Videos)
  // ==========================================
  {
    id: 'tpl-quad-2x2-grid',
    name: 'Quad 2×2 Multi-Media Grid',
    category: 'editorial-grid',
    categoryLabel: 'Multi-Media Grid',
    subtitle: '4 balanced slots for mixing multiple photos and video loops',
    description: 'A 2x2 modern editorial grid with refined margins, rounded corners, subtle shadows, and customizable captions. Perfect for outfit lookbooks and story recaps.',
    aspectRatio: 9 / 16,
    aspectLabel: '9:16 Story',
    badge: '4 Slots',
    previewThumbnail: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=800&auto=format&fit=crop',
    moodKeywords: ['Quad', '4 Photos', '4 Videos', 'Collage', '2x2', 'Grid', 'Lookbook'],
    adjustments: {
      ...defaultAdjustments,
      presetId: 'editorial-clean',
      contrast: 0.08,
      temperature: 0.04,
      vignetteAmount: 0.12,
    },
    overlays: {
      paperTexture: 'linen-white',
      backgroundColor: '#F5F2EB',
    },
    slots: [
      {
        id: 'slot-quad-1',
        label: 'Top Left (Photo/Video 1)',
        media: {
          id: 'media-quad-1',
          name: 'Look 1',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop',
          aspectRatio: 1,
          width: 800,
          height: 800,
        },
        x: 6,
        y: 8,
        width: 42,
        height: 38,
        fit: 'cover',
        borderRadius: 12,
        shadow: 'card',
        tape: 'top-center',
        zIndex: 2,
      },
      {
        id: 'slot-quad-2',
        label: 'Top Right (Photo/Video 2)',
        media: {
          id: 'media-quad-2',
          name: 'Look 2',
          type: 'video',
          url: 'https://assets.mixkit.co/videos/preview/mixkit-girl-in-neon-light-1232-large.mp4',
          aspectRatio: 1,
          width: 800,
          height: 800,
        },
        x: 52,
        y: 8,
        width: 42,
        height: 38,
        fit: 'cover',
        borderRadius: 12,
        shadow: 'card',
        tape: 'top-center',
        zIndex: 2,
      },
      {
        id: 'slot-quad-3',
        label: 'Bottom Left (Photo/Video 3)',
        media: {
          id: 'media-quad-3',
          name: 'Look 3',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=800&auto=format&fit=crop',
          aspectRatio: 1,
          width: 800,
          height: 800,
        },
        x: 6,
        y: 50,
        width: 42,
        height: 38,
        fit: 'cover',
        borderRadius: 12,
        shadow: 'card',
        zIndex: 2,
      },
      {
        id: 'slot-quad-4',
        label: 'Bottom Right (Photo/Video 4)',
        media: {
          id: 'media-quad-4',
          name: 'Look 4',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop',
          aspectRatio: 1,
          width: 800,
          height: 800,
        },
        x: 52,
        y: 50,
        width: 42,
        height: 38,
        fit: 'cover',
        borderRadius: 12,
        shadow: 'card',
        zIndex: 2,
      },
    ],
    textElements: [
      {
        id: 'txt-quad-title',
        label: 'Header Title',
        text: 'AUTUMN LOOKBOOK // 2026',
        fontFamily: 'monospaced',
        fontSize: 10,
        color: '#7E7365',
        align: 'center',
        x: 50,
        y: 3.5,
      },
      {
        id: 'txt-quad-footer',
        label: 'Footer Note',
        text: 'Tap any frame to replace photo or record video',
        fontFamily: 'modern-sans',
        fontSize: 9,
        color: '#A69480',
        align: 'center',
        x: 50,
        y: 93,
      },
    ],
  },

  // ==========================================
  // 17. 3-SLOT VERTICAL FILM STRIP TRIO
  // ==========================================
  {
    id: 'tpl-vertical-filmstrip-trio',
    name: '3-Frame Filmstrip Trio',
    category: 'polaroid-stack',
    categoryLabel: 'Film & Cinema',
    subtitle: '3 vertical cinema 35mm frames stacked with sprockets',
    description: 'Three synchronized photo and video frames in authentic 35mm film sprockets. Allows recording or uploading 3 unique moments.',
    aspectRatio: 9 / 16,
    aspectLabel: '9:16 Story',
    badge: '3 Slots',
    previewThumbnail: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=800&auto=format&fit=crop',
    moodKeywords: ['3 Frames', 'Trio', 'Filmstrip', '35mm', 'Video', 'Multi-Media'],
    adjustments: {
      ...defaultAdjustments,
      presetId: 'cinematic-35mm',
      temperature: 0.1,
      grainAmount: 0.25,
      contrast: 0.12,
    },
    overlays: {
      paperTexture: 'charcoal-dark',
      backgroundColor: '#141416',
    },
    slots: [
      {
        id: 'slot-trio-1',
        label: 'Frame 1 (Top)',
        media: {
          id: 'media-trio-1',
          name: 'Moment 1',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop',
          aspectRatio: 16 / 9,
          width: 900,
          height: 506,
        },
        x: 8,
        y: 4,
        width: 84,
        height: 27,
        fit: 'cover',
        borderStyle: 'film-35mm',
        filmBorderText: 'LUMENLAB 35MM • 01',
        shadow: 'deep',
        zIndex: 2,
      },
      {
        id: 'slot-trio-2',
        label: 'Frame 2 (Middle)',
        media: {
          id: 'media-trio-2',
          name: 'Moment 2 (Video)',
          type: 'video',
          url: 'https://assets.mixkit.co/videos/preview/mixkit-girl-in-neon-light-1232-large.mp4',
          aspectRatio: 16 / 9,
          width: 900,
          height: 506,
        },
        x: 8,
        y: 35,
        width: 84,
        height: 27,
        fit: 'cover',
        borderStyle: 'film-35mm',
        filmBorderText: 'LUMENLAB 35MM • 02',
        shadow: 'deep',
        zIndex: 2,
      },
      {
        id: 'slot-trio-3',
        label: 'Frame 3 (Bottom)',
        media: {
          id: 'media-trio-3',
          name: 'Moment 3',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop',
          aspectRatio: 16 / 9,
          width: 900,
          height: 506,
        },
        x: 8,
        y: 66,
        width: 84,
        height: 27,
        fit: 'cover',
        borderStyle: 'film-35mm',
        filmBorderText: 'LUMENLAB 35MM • 03',
        shadow: 'deep',
        zIndex: 2,
      },
    ],
    textElements: [
      {
        id: 'txt-trio-footer',
        label: 'Footer Timestamp',
        text: 'CINEMA REEL // 24FPS // ISO 400',
        fontFamily: 'monospaced',
        fontSize: 9,
        color: '#A69480',
        align: 'center',
        x: 50,
        y: 96,
      },
    ],
  },

  // ==========================================
  // 18. 6-SLOT CONTACT SHEET COLLAGE
  // ==========================================
  {
    id: 'tpl-6pack-contact-sheet',
    name: '6-Frame Darkroom Contact Sheet',
    category: 'polaroid-stack',
    categoryLabel: 'Contact Sheet',
    subtitle: '2 columns × 3 rows darkroom contact sheet for 6 pictures/videos',
    description: 'Authentic 6-slot contact sheet on dark background with red grease pencil frame markings, film edge sprockets, and batch replacement support.',
    aspectRatio: 9 / 16,
    aspectLabel: '9:16 Story',
    badge: '6 Slots',
    previewThumbnail: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop',
    moodKeywords: ['6 Slots', 'Contact Sheet', 'Darkroom', '6 Photos', '6 Videos', 'Grid', 'Proof'],
    adjustments: {
      ...defaultAdjustments,
      presetId: 'monochrome-classic',
      contrast: 0.15,
      grainAmount: 0.3,
    },
    overlays: {
      paperTexture: 'charcoal-dark',
      backgroundColor: '#101012',
    },
    slots: [
      {
        id: 'slot-cs-1',
        label: 'Frame #01',
        media: {
          id: 'media-cs-1',
          name: 'Proof 1',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop',
          aspectRatio: 1,
          width: 600,
          height: 600,
        },
        x: 6,
        y: 6,
        width: 42,
        height: 26,
        fit: 'cover',
        borderStyle: 'film-35mm',
        filmBorderText: '#01',
        zIndex: 2,
      },
      {
        id: 'slot-cs-2',
        label: 'Frame #02',
        media: {
          id: 'media-cs-2',
          name: 'Proof 2',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=800&auto=format&fit=crop',
          aspectRatio: 1,
          width: 600,
          height: 600,
        },
        x: 52,
        y: 6,
        width: 42,
        height: 26,
        fit: 'cover',
        borderStyle: 'film-35mm',
        filmBorderText: '#02',
        zIndex: 2,
      },
      {
        id: 'slot-cs-3',
        label: 'Frame #03 (Video)',
        media: {
          id: 'media-cs-3',
          name: 'Proof 3',
          type: 'video',
          url: 'https://assets.mixkit.co/videos/preview/mixkit-girl-in-neon-light-1232-large.mp4',
          aspectRatio: 1,
          width: 600,
          height: 600,
        },
        x: 6,
        y: 35,
        width: 42,
        height: 26,
        fit: 'cover',
        borderStyle: 'film-35mm',
        filmBorderText: '#03',
        zIndex: 2,
      },
      {
        id: 'slot-cs-4',
        label: 'Frame #04',
        media: {
          id: 'media-cs-4',
          name: 'Proof 4',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop',
          aspectRatio: 1,
          width: 600,
          height: 600,
        },
        x: 52,
        y: 35,
        width: 42,
        height: 26,
        fit: 'cover',
        borderStyle: 'film-35mm',
        filmBorderText: '#04',
        zIndex: 2,
      },
      {
        id: 'slot-cs-5',
        label: 'Frame #05',
        media: {
          id: 'media-cs-5',
          name: 'Proof 5',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=800&auto=format&fit=crop',
          aspectRatio: 1,
          width: 600,
          height: 600,
        },
        x: 6,
        y: 64,
        width: 42,
        height: 26,
        fit: 'cover',
        borderStyle: 'film-35mm',
        filmBorderText: '#05',
        zIndex: 2,
      },
      {
        id: 'slot-cs-6',
        label: 'Frame #06',
        media: {
          id: 'media-cs-6',
          name: 'Proof 6',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=800&auto=format&fit=crop',
          aspectRatio: 1,
          width: 600,
          height: 600,
        },
        x: 52,
        y: 64,
        width: 42,
        height: 26,
        fit: 'cover',
        borderStyle: 'film-35mm',
        filmBorderText: '#06',
        zIndex: 2,
      },
    ],
    textElements: [
      {
        id: 'txt-cs-header',
        label: 'Proof Sheet Header',
        text: 'PROOFS • LUMENLAB KODAK TX-400 • ROLL #08',
        fontFamily: 'monospaced',
        fontSize: 9,
        color: '#E03131',
        align: 'center',
        x: 50,
        y: 2.5,
      },
      {
        id: 'txt-cs-footer',
        label: 'Darkroom Note',
        text: '6-SHOT CONTACT PROOF SHEET',
        fontFamily: 'monospaced',
        fontSize: 9,
        color: '#7E7365',
        align: 'center',
        x: 50,
        y: 95.5,
      },
    ],
  },

  // ==========================================
  // 19. 2-SLOT SPLIT SCREEN (Photo + Video Duo)
  // ==========================================
  {
    id: 'tpl-split-duo-reel',
    name: 'Dual Split Screen (Side-by-Side)',
    category: 'editorial-grid',
    categoryLabel: 'Split Duo',
    subtitle: '50/50 vertical split for comparing or pairing video with photo',
    description: 'Split screen layout dividing left and right 50/50. Perfect for before/after, photo vs video, or cinematic dual perspectives.',
    aspectRatio: 9 / 16,
    aspectLabel: '9:16 Story',
    badge: '2 Slots',
    previewThumbnail: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop',
    moodKeywords: ['Split', '2 Slots', 'Duo', 'Side by Side', 'Photo & Video', 'Dual'],
    adjustments: {
      ...defaultAdjustments,
      presetId: 'editorial-warm',
      temperature: 0.08,
      contrast: 0.1,
    },
    overlays: {
      paperTexture: 'none',
      backgroundColor: '#000000',
    },
    slots: [
      {
        id: 'slot-split-left',
        label: 'Left Frame (Photo)',
        media: {
          id: 'media-split-1',
          name: 'Left Angle',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop',
          aspectRatio: 9 / 16,
          width: 600,
          height: 1200,
        },
        x: 0,
        y: 0,
        width: 49.6,
        height: 100,
        fit: 'cover',
        zIndex: 1,
      },
      {
        id: 'slot-split-right',
        label: 'Right Frame (Video)',
        media: {
          id: 'media-split-2',
          name: 'Right Motion Video',
          type: 'video',
          url: 'https://assets.mixkit.co/videos/preview/mixkit-girl-in-neon-light-1232-large.mp4',
          aspectRatio: 9 / 16,
          width: 600,
          height: 1200,
        },
        x: 50.4,
        y: 0,
        width: 49.6,
        height: 100,
        fit: 'cover',
        zIndex: 1,
      },
    ],
    textElements: [
      {
        id: 'txt-split-title',
        label: 'Center Title Tag',
        text: 'DUAL PERSPECTIVE',
        fontFamily: 'monospaced',
        fontSize: 11,
        color: '#FFFFFF',
        align: 'center',
        x: 50,
        y: 88,
        style: 'modern-box',
      },
    ],
  },

  // ==========================================
  // 20. 9-GRID INSTAGRAM BENTO MOODBOARD (9 Pictures / Videos)
  // ==========================================
  {
    id: 'tpl-9grid-instagram-bento',
    name: '9-Slot Bento Moodboard Grid',
    category: 'editorial-grid',
    categoryLabel: 'Multi-Media Grid',
    subtitle: '3×3 aesthetic Instagram grid supporting up to 9 photos & videos',
    description: 'A 3x3 moodboard grid with heart badges, like counters, and instant multi-select batch import to populate all 9 slots seamlessly.',
    aspectRatio: 9 / 16,
    aspectLabel: '9:16 Story',
    badge: '9 Slots',
    previewThumbnail: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=800&auto=format&fit=crop',
    moodKeywords: ['9 Slots', '3x3', 'Bento', 'Moodboard', 'Instagram', 'Collage', '9 Photos'],
    adjustments: {
      ...defaultAdjustments,
      presetId: 'inso',
      contrast: 0.06,
      temperature: 0.05,
    },
    overlays: {
      paperTexture: 'linen-white',
      backgroundColor: '#FAF9F6',
    },
    slots: [
      { id: 's9-1', label: 'Slot 1', media: { id: 'm9-1', name: '1', type: 'image', url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=500&auto=format&fit=crop', aspectRatio: 1, width: 400, height: 400 }, x: 5, y: 10, width: 28, height: 24, fit: 'cover', borderRadius: 8, shadow: 'subtle', heartBadge: true, likeCount: '1.2k', zIndex: 2 },
      { id: 's9-2', label: 'Slot 2 (Video)', media: { id: 'm9-2', name: '2', type: 'video', url: 'https://assets.mixkit.co/videos/preview/mixkit-girl-in-neon-light-1232-large.mp4', aspectRatio: 1, width: 400, height: 400 }, x: 36, y: 10, width: 28, height: 24, fit: 'cover', borderRadius: 8, shadow: 'subtle', heartBadge: true, likeCount: '3.4k', zIndex: 2 },
      { id: 's9-3', label: 'Slot 3', media: { id: 'm9-3', name: '3', type: 'image', url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=500&auto=format&fit=crop', aspectRatio: 1, width: 400, height: 400 }, x: 67, y: 10, width: 28, height: 24, fit: 'cover', borderRadius: 8, shadow: 'subtle', heartBadge: true, likeCount: '890', zIndex: 2 },
      
      { id: 's9-4', label: 'Slot 4', media: { id: 'm9-4', name: '4', type: 'image', url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=500&auto=format&fit=crop', aspectRatio: 1, width: 400, height: 400 }, x: 5, y: 37, width: 28, height: 24, fit: 'cover', borderRadius: 8, shadow: 'subtle', heartBadge: true, likeCount: '2.1k', zIndex: 2 },
      { id: 's9-5', label: 'Slot 5', media: { id: 'm9-5', name: '5', type: 'image', url: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=500&auto=format&fit=crop', aspectRatio: 1, width: 400, height: 400 }, x: 36, y: 37, width: 28, height: 24, fit: 'cover', borderRadius: 8, shadow: 'subtle', heartBadge: true, likeCount: '4.8k', zIndex: 2 },
      { id: 's9-6', label: 'Slot 6 (Video)', media: { id: 'm9-6', name: '6', type: 'video', url: 'https://assets.mixkit.co/videos/preview/mixkit-girl-in-neon-light-1232-large.mp4', aspectRatio: 1, width: 400, height: 400 }, x: 67, y: 37, width: 28, height: 24, fit: 'cover', borderRadius: 8, shadow: 'subtle', heartBadge: true, likeCount: '1.9k', zIndex: 2 },
      
      { id: 's9-7', label: 'Slot 7', media: { id: 'm9-7', name: '7', type: 'image', url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=500&auto=format&fit=crop', aspectRatio: 1, width: 400, height: 400 }, x: 5, y: 64, width: 28, height: 24, fit: 'cover', borderRadius: 8, shadow: 'subtle', heartBadge: true, likeCount: '950', zIndex: 2 },
      { id: 's9-8', label: 'Slot 8', media: { id: 'm9-8', name: '8', type: 'image', url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=500&auto=format&fit=crop', aspectRatio: 1, width: 400, height: 400 }, x: 36, y: 64, width: 28, height: 24, fit: 'cover', borderRadius: 8, shadow: 'subtle', heartBadge: true, likeCount: '5.2k', zIndex: 2 },
      { id: 's9-9', label: 'Slot 9', media: { id: 'm9-9', name: '9', type: 'image', url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=500&auto=format&fit=crop', aspectRatio: 1, width: 400, height: 400 }, x: 67, y: 64, width: 28, height: 24, fit: 'cover', borderRadius: 8, shadow: 'subtle', heartBadge: true, likeCount: '3.1k', zIndex: 2 },
    ],
    textElements: [
      {
        id: 'txt-9g-title',
        label: 'Grid Header',
        text: 'CURATED MOODBOARD // 9 FRAMES',
        fontFamily: 'monospaced',
        fontSize: 10,
        color: '#2A2723',
        align: 'center',
        x: 50,
        y: 4.5,
      },
      {
        id: 'txt-9g-footer',
        label: 'Batch Action Note',
        text: 'Tap any slot to replace or use "Batch Fill" to load all at once',
        fontFamily: 'modern-sans',
        fontSize: 8.5,
        color: '#7E7365',
        align: 'center',
        x: 50,
        y: 93,
      },
    ],
  },
];
