import { Preset, MediaItem } from '../types';
import { defaultAdjustments, defaultHSL } from './defaultAdjustments';

export const BUILT_IN_PRESETS: Preset[] = [
  {
    id: 'none',
    name: 'Original',
    category: 'LumenLab Signature',
    description: 'Zero adjustments applied. Natural raw capture.',
    thumbnailColor: '#555555',
    adjustments: {
      ...defaultAdjustments,
      presetId: 'none',
    },
  },
  {
    id: 'inso',
    name: 'INSO',
    category: 'LumenLab Signature',
    badge: 'Iconic',
    description: 'LumenLab’s legendary sun-kissed signature. Warm golden highlights, soft contrast, nostalgic vintage film tones.',
    thumbnailColor: '#DDA15E',
    adjustments: {
      ...defaultAdjustments,
      presetId: 'inso',
      exposure: 0.08,
      contrast: 0.12,
      highlights: -0.15,
      shadows: 0.22,
      whites: -0.05,
      blacks: 0.1,
      temperature: 0.28,
      tint: 0.08,
      saturation: 0.05,
      vibrance: 0.22,
      grainAmount: 0.18,
      grainSize: 1.1,
      glowAmount: 0.15,
      vignetteAmount: 0.12,
      hsl: {
        ...defaultHSL,
        orange: { hue: -0.05, saturation: 0.15, luminance: 0.08 },
        yellow: { hue: -0.1, saturation: 0.1, luminance: 0.05 },
        green: { hue: 0.15, saturation: -0.2, luminance: -0.05 },
        blue: { hue: -0.1, saturation: -0.15, luminance: -0.05 },
      },
      curves: {
        master: [{ x: 0, y: 0.06 }, { x: 0.25, y: 0.28 }, { x: 0.75, y: 0.78 }, { x: 1, y: 0.96 }],
        red: [{ x: 0, y: 0.04 }, { x: 0.5, y: 0.52 }, { x: 1, y: 1 }],
        green: [{ x: 0, y: 0 }, { x: 0.5, y: 0.49 }, { x: 1, y: 0.98 }],
        blue: [{ x: 0, y: 0.02 }, { x: 0.5, y: 0.46 }, { x: 1, y: 0.92 }],
      },
    },
  },
  {
    id: 'yum',
    name: 'YUM',
    category: 'LumenLab Signature',
    badge: 'Popular',
    description: 'Deep, rich chocolate undertones, creamy skin highlights, and high-impact editorial warmth.',
    thumbnailColor: '#BC6C25',
    adjustments: {
      ...defaultAdjustments,
      presetId: 'yum',
      exposure: 0.04,
      contrast: 0.24,
      highlights: -0.25,
      shadows: 0.18,
      whites: 0.08,
      blacks: -0.08,
      temperature: 0.32,
      tint: 0.04,
      saturation: 0.12,
      vibrance: 0.18,
      grainAmount: 0.22,
      grainSize: 1.2,
      glowAmount: 0.18,
      vignetteAmount: 0.2,
      hsl: {
        ...defaultHSL,
        orange: { hue: -0.08, saturation: 0.2, luminance: 0.06 },
        yellow: { hue: -0.15, saturation: 0.12, luminance: -0.04 },
        green: { hue: 0.2, saturation: -0.3, luminance: -0.1 },
        blue: { hue: -0.12, saturation: -0.25, luminance: -0.15 },
      },
      curves: {
        master: [{ x: 0, y: 0.04 }, { x: 0.3, y: 0.26 }, { x: 0.7, y: 0.76 }, { x: 1, y: 1 }],
        red: [{ x: 0, y: 0.02 }, { x: 0.5, y: 0.54 }, { x: 1, y: 1 }],
        green: [{ x: 0, y: 0 }, { x: 0.5, y: 0.48 }, { x: 1, y: 0.96 }],
        blue: [{ x: 0, y: 0 }, { x: 0.5, y: 0.42 }, { x: 1, y: 0.9 }],
      },
    },
  },
  {
    id: 'fresh',
    name: 'FRESH',
    category: 'Editorial',
    badge: 'Clean',
    description: 'Crisp editorial clean aesthetic with pure whites, vibrant greens and radiant skin tones.',
    thumbnailColor: '#E9D8A6',
    adjustments: {
      ...defaultAdjustments,
      presetId: 'fresh',
      exposure: 0.12,
      contrast: 0.08,
      highlights: 0.1,
      shadows: 0.14,
      whites: 0.15,
      blacks: -0.02,
      temperature: -0.06,
      tint: 0.02,
      saturation: 0.08,
      vibrance: 0.25,
      clarity: 0.1,
      grainAmount: 0.08,
      hsl: {
        ...defaultHSL,
        orange: { hue: 0.02, saturation: 0.08, luminance: 0.12 },
        yellow: { hue: 0.05, saturation: 0.05, luminance: 0.08 },
        green: { hue: -0.05, saturation: 0.18, luminance: 0.05 },
        blue: { hue: 0.05, saturation: 0.12, luminance: 0.04 },
      },
      curves: {
        master: [{ x: 0, y: 0 }, { x: 0.25, y: 0.23 }, { x: 0.75, y: 0.8 }, { x: 1, y: 1 }],
        red: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
        green: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
        blue: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
      },
    },
  },
  {
    id: 'lush',
    name: 'LUSH',
    category: 'Editorial',
    description: 'Dreamy, ethereal film halation with pastel greens, creamy highlights, and soft matte blacks.',
    thumbnailColor: '#94D2BD',
    adjustments: {
      ...defaultAdjustments,
      presetId: 'lush',
      exposure: 0.1,
      contrast: -0.05,
      highlights: -0.18,
      shadows: 0.25,
      whites: -0.08,
      blacks: 0.15,
      temperature: 0.1,
      tint: -0.06,
      saturation: -0.04,
      vibrance: 0.15,
      glowAmount: 0.28,
      glowRadius: 0.65,
      grainAmount: 0.15,
      hsl: {
        ...defaultHSL,
        green: { hue: 0.2, saturation: 0.15, luminance: 0.05 },
        yellow: { hue: 0.1, saturation: -0.05, luminance: 0.08 },
        orange: { hue: 0, saturation: 0.05, luminance: 0.08 },
      },
      curves: {
        master: [{ x: 0, y: 0.08 }, { x: 0.35, y: 0.38 }, { x: 0.8, y: 0.82 }, { x: 1, y: 0.94 }],
        red: [{ x: 0, y: 0.02 }, { x: 0.5, y: 0.49 }, { x: 1, y: 1 }],
        green: [{ x: 0, y: 0.04 }, { x: 0.5, y: 0.52 }, { x: 1, y: 1 }],
        blue: [{ x: 0, y: 0.03 }, { x: 0.5, y: 0.48 }, { x: 1, y: 0.96 }],
      },
    },
  },
  {
    id: '1984',
    name: '1984',
    category: 'Vintage Film',
    badge: 'Retro',
    description: 'Authentic 80s analog 35mm film stock with faded emulsion, magenta shadow split, and warm grain.',
    thumbnailColor: '#E76F51',
    adjustments: {
      ...defaultAdjustments,
      presetId: '1984',
      exposure: 0.05,
      contrast: 0.16,
      highlights: -0.2,
      shadows: 0.3,
      whites: -0.1,
      blacks: 0.2,
      temperature: 0.18,
      tint: 0.14,
      saturation: -0.08,
      vibrance: 0.1,
      grainAmount: 0.32,
      grainSize: 1.4,
      grainRoughness: 0.6,
      prismAmount: 0.12,
      vignetteAmount: 0.18,
      curves: {
        master: [{ x: 0, y: 0.1 }, { x: 0.3, y: 0.32 }, { x: 0.7, y: 0.75 }, { x: 1, y: 0.92 }],
        red: [{ x: 0, y: 0.08 }, { x: 0.5, y: 0.54 }, { x: 1, y: 0.98 }],
        green: [{ x: 0, y: 0.02 }, { x: 0.5, y: 0.48 }, { x: 1, y: 0.94 }],
        blue: [{ x: 0, y: 0.05 }, { x: 0.5, y: 0.44 }, { x: 1, y: 0.88 }],
      },
    },
  },
  {
    id: 'almond',
    name: 'ALMOND',
    category: 'Golden & Warm',
    description: 'Muted neutral beige & cappuccino tones. Low saturation, high-key editorial elegance.',
    thumbnailColor: '#DDBEA9',
    adjustments: {
      ...defaultAdjustments,
      presetId: 'almond',
      exposure: 0.15,
      contrast: -0.08,
      highlights: -0.1,
      shadows: 0.2,
      whites: -0.05,
      blacks: 0.08,
      temperature: 0.22,
      tint: 0.02,
      saturation: -0.2,
      vibrance: -0.05,
      grainAmount: 0.14,
      hsl: {
        ...defaultHSL,
        orange: { hue: -0.04, saturation: -0.1, luminance: 0.1 },
        yellow: { hue: -0.12, saturation: -0.25, luminance: 0.06 },
        green: { hue: 0.1, saturation: -0.4, luminance: -0.05 },
        blue: { hue: 0, saturation: -0.5, luminance: 0 },
      },
      curves: {
        master: [{ x: 0, y: 0.05 }, { x: 0.5, y: 0.52 }, { x: 1, y: 0.96 }],
        red: [{ x: 0, y: 0.02 }, { x: 0.5, y: 0.51 }, { x: 1, y: 1 }],
        green: [{ x: 0, y: 0 }, { x: 0.5, y: 0.49 }, { x: 1, y: 0.98 }],
        blue: [{ x: 0, y: 0 }, { x: 0.5, y: 0.46 }, { x: 1, y: 0.92 }],
      },
    },
  },
  {
    id: 'cocoa',
    name: 'COCOA',
    category: 'Golden & Warm',
    badge: 'Bronze',
    description: 'Sumptuous deep bronzed skin, espresso tones, golden amber sunlight.',
    thumbnailColor: '#A56644',
    adjustments: {
      ...defaultAdjustments,
      presetId: 'cocoa',
      exposure: 0.02,
      contrast: 0.26,
      highlights: -0.28,
      shadows: 0.12,
      whites: 0.05,
      blacks: -0.05,
      temperature: 0.38,
      tint: 0.06,
      saturation: 0.15,
      vibrance: 0.2,
      grainAmount: 0.2,
      vignetteAmount: 0.25,
      hsl: {
        ...defaultHSL,
        orange: { hue: -0.08, saturation: 0.25, luminance: 0.02 },
        yellow: { hue: -0.18, saturation: 0.18, luminance: -0.06 },
        green: { hue: 0.15, saturation: -0.35, luminance: -0.15 },
        blue: { hue: -0.1, saturation: -0.3, luminance: -0.2 },
      },
      curves: {
        master: [{ x: 0, y: 0.02 }, { x: 0.3, y: 0.24 }, { x: 0.7, y: 0.76 }, { x: 1, y: 1 }],
        red: [{ x: 0, y: 0.04 }, { x: 0.5, y: 0.56 }, { x: 1, y: 1 }],
        green: [{ x: 0, y: 0 }, { x: 0.5, y: 0.47 }, { x: 1, y: 0.95 }],
        blue: [{ x: 0, y: 0 }, { x: 0.5, y: 0.4 }, { x: 1, y: 0.88 }],
      },
    },
  },
  {
    id: 'petal',
    name: 'PETAL',
    category: 'Editorial',
    description: 'Ethereal romantic rose champagne tint, soft highlight diffusion, and pastel glow.',
    thumbnailColor: '#F4A261',
    adjustments: {
      ...defaultAdjustments,
      presetId: 'petal',
      exposure: 0.1,
      contrast: 0.02,
      highlights: -0.12,
      shadows: 0.18,
      whites: -0.04,
      blacks: 0.06,
      temperature: 0.12,
      tint: 0.22,
      saturation: 0.04,
      vibrance: 0.16,
      glowAmount: 0.24,
      grainAmount: 0.14,
      hsl: {
        ...defaultHSL,
        red: { hue: 0.05, saturation: 0.12, luminance: 0.08 },
        magenta: { hue: -0.05, saturation: 0.18, luminance: 0.05 },
        orange: { hue: 0.02, saturation: 0.08, luminance: 0.06 },
        green: { hue: 0.1, saturation: -0.25, luminance: 0 },
      },
      curves: {
        master: [{ x: 0, y: 0.05 }, { x: 0.4, y: 0.42 }, { x: 1, y: 0.98 }],
        red: [{ x: 0, y: 0.06 }, { x: 0.5, y: 0.55 }, { x: 1, y: 1 }],
        green: [{ x: 0, y: 0.01 }, { x: 0.5, y: 0.48 }, { x: 1, y: 0.96 }],
        blue: [{ x: 0, y: 0.04 }, { x: 0.5, y: 0.5 }, { x: 1, y: 0.94 }],
      },
    },
  },
  {
    id: 'noir',
    name: 'NOIR',
    category: 'Moody & B&W',
    badge: 'B&W',
    description: 'High-contrast monochrome film with deep rich blacks, sharp midtones, and silver grain.',
    thumbnailColor: '#2B2B2B',
    adjustments: {
      ...defaultAdjustments,
      presetId: 'noir',
      exposure: 0.05,
      contrast: 0.35,
      highlights: -0.1,
      shadows: -0.08,
      whites: 0.18,
      blacks: -0.15,
      temperature: 0,
      tint: 0,
      saturation: -1.0,
      vibrance: -1.0,
      clarity: 0.22,
      grainAmount: 0.38,
      grainSize: 1.3,
      vignetteAmount: 0.22,
      curves: {
        master: [{ x: 0, y: 0.02 }, { x: 0.25, y: 0.18 }, { x: 0.75, y: 0.82 }, { x: 1, y: 1 }],
        red: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
        green: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
        blue: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
      },
    },
  },
  {
    id: 'retro90s',
    name: 'RETRO 90s',
    category: 'Vintage Film',
    badge: 'Nostalgia',
    description: 'Point-and-shoot disposable camera aesthetics with yellowish-green undertones and flash pop.',
    thumbnailColor: '#E9C46A',
    adjustments: {
      ...defaultAdjustments,
      presetId: 'retro90s',
      exposure: 0.08,
      contrast: 0.2,
      highlights: 0.15,
      shadows: 0.22,
      whites: 0.1,
      blacks: 0.12,
      temperature: 0.24,
      tint: -0.08,
      saturation: 0.18,
      vibrance: 0.15,
      grainAmount: 0.35,
      grainSize: 1.5,
      dustType: 'fine-specks',
      dustAmount: 0.25,
      lightLeakType: 'sunset',
      lightLeakAmount: 0.2,
      curves: {
        master: [{ x: 0, y: 0.08 }, { x: 0.28, y: 0.3 }, { x: 0.72, y: 0.76 }, { x: 1, y: 0.95 }],
        red: [{ x: 0, y: 0.04 }, { x: 0.5, y: 0.53 }, { x: 1, y: 1 }],
        green: [{ x: 0, y: 0.06 }, { x: 0.5, y: 0.52 }, { x: 1, y: 0.98 }],
        blue: [{ x: 0, y: 0.01 }, { x: 0.5, y: 0.42 }, { x: 1, y: 0.88 }],
      },
    },
  },
  {
    id: 'golden',
    name: 'GOLDEN',
    category: 'Golden & Warm',
    badge: 'Magic Hour',
    description: 'Endless golden hour sunset glow. Enhances skin warmth and bathes shadows in golden honey.',
    thumbnailColor: '#F7B267',
    adjustments: {
      ...defaultAdjustments,
      presetId: 'golden',
      exposure: 0.06,
      contrast: 0.15,
      highlights: -0.15,
      shadows: 0.2,
      whites: 0.04,
      blacks: 0.02,
      temperature: 0.45,
      tint: 0.1,
      saturation: 0.14,
      vibrance: 0.28,
      glowAmount: 0.22,
      grainAmount: 0.15,
      lightLeakType: 'side-flare',
      lightLeakAmount: 0.18,
      hsl: {
        ...defaultHSL,
        orange: { hue: -0.06, saturation: 0.22, luminance: 0.1 },
        yellow: { hue: -0.12, saturation: 0.2, luminance: 0.08 },
        red: { hue: 0.04, saturation: 0.16, luminance: 0.04 },
      },
    },
  },
  {
    id: 'moodyblue',
    name: 'MOODY BLUE',
    category: 'Moody & B&W',
    description: 'Cinematic deep teal shadows with warm amber skin tones for a high-fashion look.',
    thumbnailColor: '#264653',
    adjustments: {
      ...defaultAdjustments,
      presetId: 'moodyblue',
      exposure: -0.02,
      contrast: 0.28,
      highlights: -0.22,
      shadows: 0.1,
      whites: 0.06,
      blacks: -0.08,
      temperature: -0.12,
      tint: 0.05,
      saturation: 0.02,
      vibrance: 0.12,
      grainAmount: 0.24,
      vignetteAmount: 0.28,
      hsl: {
        ...defaultHSL,
        orange: { hue: -0.04, saturation: 0.2, luminance: 0.06 },
        blue: { hue: -0.1, saturation: 0.25, luminance: -0.15 },
        cyan: { hue: -0.05, saturation: 0.3, luminance: -0.1 },
      },
      curves: {
        master: [{ x: 0, y: 0.03 }, { x: 0.3, y: 0.26 }, { x: 0.7, y: 0.74 }, { x: 1, y: 1 }],
        red: [{ x: 0, y: 0 }, { x: 0.5, y: 0.48 }, { x: 1, y: 1 }],
        green: [{ x: 0, y: 0.02 }, { x: 0.5, y: 0.5 }, { x: 1, y: 0.98 }],
        blue: [{ x: 0, y: 0.08 }, { x: 0.5, y: 0.54 }, { x: 1, y: 0.95 }],
      },
    },
  },
  {
    id: 'kodak400',
    name: 'PORTRA 400',
    category: 'Vintage Film',
    badge: 'Film',
    description: 'The standard of editorial portraiture. Balanced skin tones, natural contrast, and creamy latitude.',
    thumbnailColor: '#D4A373',
    adjustments: {
      ...defaultAdjustments,
      presetId: 'kodak400',
      exposure: 0.06,
      contrast: 0.1,
      highlights: -0.12,
      shadows: 0.16,
      whites: -0.02,
      blacks: 0.06,
      temperature: 0.16,
      tint: 0.06,
      saturation: 0.08,
      vibrance: 0.18,
      grainAmount: 0.25,
      grainSize: 1.2,
      grainRoughness: 0.5,
      glowAmount: 0.12,
      hsl: {
        ...defaultHSL,
        orange: { hue: -0.03, saturation: 0.12, luminance: 0.08 },
        yellow: { hue: -0.06, saturation: 0.08, luminance: 0.04 },
        green: { hue: 0.1, saturation: -0.15, luminance: -0.02 },
      },
      curves: {
        master: [{ x: 0, y: 0.04 }, { x: 0.25, y: 0.26 }, { x: 0.75, y: 0.78 }, { x: 1, y: 0.98 }],
        red: [{ x: 0, y: 0.03 }, { x: 0.5, y: 0.52 }, { x: 1, y: 1 }],
        green: [{ x: 0, y: 0.01 }, { x: 0.5, y: 0.5 }, { x: 1, y: 0.98 }],
        blue: [{ x: 0, y: 0.02 }, { x: 0.5, y: 0.47 }, { x: 1, y: 0.94 }],
      },
    },
  },
];

export const SAMPLE_MEDIA_GALLERY: MediaItem[] = [
  {
    id: 'sample-editorial-1',
    name: 'Amalfi Coast Golden Hour',
    type: 'image',
    url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1200&auto=format&fit=crop',
    aspectRatio: 3 / 4,
    width: 1200,
    height: 1600,
  },
  {
    id: 'sample-editorial-2',
    name: 'Vintage Convertible & Sun',
    type: 'image',
    url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1200&auto=format&fit=crop',
    aspectRatio: 16 / 9,
    width: 1200,
    height: 675,
  },
  {
    id: 'sample-editorial-3',
    name: 'Parisian Café Summer',
    type: 'image',
    url: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=1200&auto=format&fit=crop',
    aspectRatio: 4 / 5,
    width: 1200,
    height: 1500,
  },
  {
    id: 'sample-editorial-4',
    name: 'Editorial Fashion Portrait',
    type: 'image',
    url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1200&auto=format&fit=crop',
    aspectRatio: 4 / 5,
    width: 1200,
    height: 1500,
  },
  {
    id: 'sample-editorial-5',
    name: 'Sunlight Shadows & Linen',
    type: 'image',
    url: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1200&auto=format&fit=crop',
    aspectRatio: 3 / 4,
    width: 1200,
    height: 1600,
  },
  {
    id: 'sample-video-1',
    name: 'Golden Hour Ocean Waves (Video)',
    type: 'video',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    aspectRatio: 16 / 9,
    width: 1280,
    height: 720,
    duration: 15,
  },
  {
    id: 'sample-video-2',
    name: 'Cinematic Escapade (Video)',
    type: 'video',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    aspectRatio: 16 / 9,
    width: 1280,
    height: 720,
    duration: 15,
  }
];
