import { ProjectTemplate, ProjectTemplateTag } from '../types';
import { defaultAdjustments, defaultHSL } from './defaultAdjustments';
import { COLLAGE_TEMPLATES } from './collageTemplates';

export const PROJECT_TEMPLATE_TAGS: {
  id: ProjectTemplateTag;
  label: string;
  color: string;
  bgColor: string;
  iconName: string;
  description: string;
}[] = [
  {
    id: 'clean',
    label: 'Clean',
    color: '#2A2723',
    bgColor: '#F0EEE6',
    iconName: 'Sparkles',
    description: 'Crisp minimal aesthetics, high-key whites, pure neutrals and sleek editorial framing.',
  },
  {
    id: 'souveniers',
    label: 'Souveniers',
    color: '#B45309',
    bgColor: '#FEF3C7',
    iconName: 'Compass',
    description: 'Retro postcard scrapbook tones, 35mm sprocket borders, amber LED date stamps, nostalgic travel memories.',
  },
  {
    id: 'sunbath',
    label: 'Sunbath',
    color: '#D97706',
    bgColor: '#FFFBEB',
    iconName: 'Sun',
    description: 'Golden hour sunkissed warmth, amber light leaks, radiant skin glow, nostalgic summer radiance.',
  },
  {
    id: 'love letters',
    label: 'Love Letters',
    color: '#DB2777',
    bgColor: '#FDF2F8',
    iconName: 'Heart',
    description: 'Dreamy romantic pastel haze, soft rosewater split tones, delicate grain, handwritten journal vibes.',
  },
  {
    id: 'film classic',
    label: 'Film Classic',
    color: '#92400E',
    bgColor: '#FDE68A',
    iconName: 'Film',
    description: 'Authentic 35mm Kodak Portra emulation, rich organic grain, analog highlight rolloff, timeless film border.',
  },
  {
    id: 'film white',
    label: 'Film White',
    color: '#475569',
    bgColor: '#F1F5F9',
    iconName: 'Layers',
    description: 'Milky high-key whites, soft highlight blooming, gentle contrast lift, editorial linen framing.',
  },
  {
    id: 'editorial',
    label: 'Editorial',
    color: '#18181B',
    bgColor: '#E4E4E7',
    iconName: 'Eye',
    description: 'High-fashion lookbook contrast, stark monochrome or punchy tones, bold visual direction.',
  },
  {
    id: 'sketch',
    label: 'Sketch',
    color: '#52525B',
    bgColor: '#F4F4F5',
    iconName: 'PenTool',
    description: 'Artistic textured grain, charcoal/sepia paper grading, vintage scratches, handcrafted analog sketch mood.',
  },
  {
    id: 'cyber',
    label: 'Cyber',
    color: '#0284C7',
    bgColor: '#E0F2FE',
    iconName: 'Zap',
    description: 'Y2K chromatic aberration, neon cyan-magenta shift, futuristic VHS scanlines, camcorder HUD overlays.',
  },
  {
    id: 'pride',
    label: 'Pride',
    color: '#7C3AED',
    bgColor: '#F3E8FF',
    iconName: 'Rainbow',
    description: 'Vibrant chromatic spectrum, joyful multi-hue saturation, rainbow prism flares, celebratory radiance.',
  },
  {
    id: 'airdrop',
    label: 'AirDrop',
    color: '#0A84FF',
    bgColor: '#E5F2FF',
    iconName: 'Smartphone',
    description: 'Interactive iOS AirDrop dialog cards with customizable preview photos and accept/decline buttons.',
  },
  {
    id: 'notebook',
    label: 'Notebook & Binder',
    color: '#78350F',
    bgColor: '#FEF3C7',
    iconName: 'BookOpen',
    description: 'Metallic spiral notebook bindings, chrome 4-ring binder lookbooks, and textured sketch paper.',
  },
  {
    id: 'scrapbook',
    label: 'Washi & Scrapbook',
    color: '#B45309',
    bgColor: '#FFFBEB',
    iconName: 'Paperclip',
    description: 'Translucent washi tape, metallic paperclips, typewriter sale cards, and hand-drawn doodles.',
  },
  {
    id: 'polaroid',
    label: 'Polaroid & Film',
    color: '#374151',
    bgColor: '#F3F4F6',
    iconName: 'Film',
    description: 'Offset Polaroid instant photo stacks, 35mm cinema film reels with sprockets, and 6-pack contact sheets.',
  },
  {
    id: 'bento',
    label: 'Editorial Bento',
    color: '#18181B',
    bgColor: '#F4F4F5',
    iconName: 'Grid',
    description: '9-grid Instagram feeds with like hearts and asymmetric multi-slot lookbook magazine layouts.',
  },
  {
    id: 'handwritten',
    label: 'Handwritten Script',
    color: '#4B5563',
    bgColor: '#F9FAFB',
    iconName: 'PenTool',
    description: 'Calligraphy quotes, handwritten journal scribbles, and intimate story captions.',
  },
];

export const LUMENLAB_PROJECT_TEMPLATES: ProjectTemplate[] = [
  // ==========================================
  // 1. CLEAN
  // ==========================================
  {
    id: 'template-clean-studio',
    name: 'Clean Studio Minimal',
    tag: 'clean',
    tagLabel: 'Clean',
    tagColor: '#2A2723',
    tagBgColor: '#F0EEE6',
    subtitle: 'High-key studio clarity & crisp neutral whites',
    description: 'Pristine editorial lighting with pure whites, lifted skin tones, subtle sharpening, and a clean editorial white matting border.',
    aspectRatio: 4 / 5,
    aspectLabel: '4:5 Portrait',
    badge: 'Popular',
    moodKeywords: ['Minimal', 'Studio', 'Pure Whites', 'Editorial'],
    previewThumbnail: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=800&auto=format&fit=crop',
    sampleMedia: {
      id: 'media-clean-1',
      name: 'Clean Studio Lookbook',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1200&auto=format&fit=crop',
      aspectRatio: 4 / 5,
      width: 1200,
      height: 1500,
    },
    adjustments: {
      ...defaultAdjustments,
      presetId: 'fresh',
      exposure: 0.1,
      contrast: 0.08,
      highlights: -0.1,
      shadows: 0.15,
      whites: 0.12,
      blacks: 0.05,
      temperature: -0.04,
      tint: 0.02,
      saturation: -0.05,
      vibrance: 0.12,
      clarity: 0.2,
      grainAmount: 0.06,
      grainSize: 0.9,
      frameType: 'gallery-white',
      frameWidth: 0.04,
      dateStamp: {
        ...defaultAdjustments.dateStamp,
        enabled: true,
        style: 'classic-white',
        position: 'bottom-right',
        includeTime: false,
        size: 0.9,
        opacity: 0.85,
      },
    },
  },
  {
    id: 'template-clean-nordic',
    name: 'Nordic Light Architecture',
    tag: 'clean',
    tagLabel: 'Clean',
    tagColor: '#2A2723',
    tagBgColor: '#F0EEE6',
    subtitle: 'Airy serene brightness & architectural simplicity',
    description: 'Bright airy highlight rolloff with subtle cool undertones, minimal distortion, and clean linen borders.',
    aspectRatio: 1 / 1,
    aspectLabel: '1:1 Square',
    moodKeywords: ['Airy', 'Nordic', 'Zen', 'Modern'],
    previewThumbnail: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=800&auto=format&fit=crop',
    sampleMedia: {
      id: 'media-clean-2',
      name: 'Nordic Light Interior',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=1200&auto=format&fit=crop',
      aspectRatio: 1 / 1,
      width: 1200,
      height: 1200,
    },
    adjustments: {
      ...defaultAdjustments,
      presetId: 'sage',
      exposure: 0.14,
      contrast: -0.06,
      highlights: -0.18,
      shadows: 0.22,
      temperature: -0.08,
      vibrance: 0.08,
      glowAmount: 0.1,
      grainAmount: 0.04,
      frameType: 'gallery-cream',
      frameWidth: 0.05,
    },
  },

  // ==========================================
  // 2. SOUVENIERS
  // ==========================================
  {
    id: 'template-souveniers-postcard',
    name: 'Roma Postcard Memories',
    tag: 'souveniers',
    tagLabel: 'Souveniers',
    tagColor: '#B45309',
    tagBgColor: '#FEF3C7',
    subtitle: 'Italian summer scrapbook & 35mm sprocket border',
    description: 'Nostalgic European travel memories with golden hour warmth, 35mm film perforations, vintage dust specks, and authentic 90s LED date stamp.',
    aspectRatio: 3 / 4,
    aspectLabel: '3:4 Classic',
    badge: 'Iconic',
    moodKeywords: ['Travel', 'Postcard', '35mm Film', 'Nostalgia', 'Scrapbook'],
    previewThumbnail: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=800&auto=format&fit=crop',
    sampleMedia: {
      id: 'media-souveniers-1',
      name: 'Amalfi Coast Memory',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1200&auto=format&fit=crop',
      aspectRatio: 3 / 4,
      width: 1200,
      height: 1600,
    },
    adjustments: {
      ...defaultAdjustments,
      presetId: '1984',
      cameraType: 'fling35',
      exposure: 0.08,
      contrast: 0.16,
      highlights: -0.2,
      shadows: 0.18,
      temperature: 0.32,
      tint: 0.06,
      vibrance: 0.2,
      grainAmount: 0.32,
      grainSize: 1.25,
      dustType: 'vintage-dust',
      dustAmount: 0.28,
      lightLeakType: 'sunset',
      lightLeakAmount: 0.35,
      frameType: 'film-35mm',
      frameWidth: 0.06,
      dateStamp: {
        enabled: true,
        style: 'led-orange',
        position: 'bottom-right',
        includeTime: false,
        customDate: '1998-08-15',
        size: 1.05,
        opacity: 0.95,
      },
    },
  },
  {
    id: 'template-souveniers-polaroid',
    name: 'Vintage Travel Scrapbook',
    tag: 'souveniers',
    tagLabel: 'Souveniers',
    tagColor: '#B45309',
    tagBgColor: '#FEF3C7',
    subtitle: 'Classic Polaroid instant framing & vacation memories',
    description: 'Instant film framing with wide bottom chin, warm sun-faded tones, soft contrast, and handwritten aesthetic mood.',
    aspectRatio: 4 / 5,
    aspectLabel: '4:5 Portrait',
    moodKeywords: ['Polaroid', 'Vacation', 'Warm Sun', 'Scrapbook'],
    previewThumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
    sampleMedia: {
      id: 'media-souveniers-2',
      name: 'Retro Convertible Summer',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1200&auto=format&fit=crop',
      aspectRatio: 16 / 9,
      width: 1200,
      height: 675,
    },
    adjustments: {
      ...defaultAdjustments,
      presetId: 'dazed',
      cameraType: 'polaroid',
      exposure: 0.12,
      contrast: -0.05,
      highlights: -0.22,
      shadows: 0.28,
      temperature: 0.25,
      tint: 0.08,
      vibrance: 0.15,
      glowAmount: 0.22,
      grainAmount: 0.26,
      frameType: 'polaroid',
      frameWidth: 0.08,
      dateStamp: {
        enabled: true,
        style: 'led-red',
        position: 'bottom-left',
        includeTime: false,
        customDate: '1999-07-24',
        size: 0.95,
        opacity: 0.9,
      },
    },
  },

  // ==========================================
  // 3. SUNBATH
  // ==========================================
  {
    id: 'template-sunbath-golden',
    name: 'Golden Hour Sunkiss',
    tag: 'sunbath',
    tagLabel: 'Sunbath',
    tagColor: '#D97706',
    tagBgColor: '#FFFBEB',
    subtitle: 'Warm golden glow, sunset leaks & bronze skin tones',
    description: 'LumenLab signature sun-drenched aesthetic with deep warm amber highlights, glowing sunset light flares, radiant skin tones, and rich analog contrast.',
    aspectRatio: 9 / 16,
    aspectLabel: '9:16 Story / Reel',
    badge: 'Best Seller',
    moodKeywords: ['Golden Hour', 'Sunkissed', 'Amber Glow', 'Bronze', 'Sunset'],
    previewThumbnail: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=800&auto=format&fit=crop',
    sampleMedia: {
      id: 'media-sunbath-1',
      name: 'Sunlight Parisian Afternoon',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=1200&auto=format&fit=crop',
      aspectRatio: 4 / 5,
      width: 1200,
      height: 1500,
    },
    adjustments: {
      ...defaultAdjustments,
      presetId: 'inso',
      cameraType: 'calagold',
      exposure: 0.1,
      contrast: 0.18,
      highlights: -0.22,
      shadows: 0.24,
      whites: 0.06,
      blacks: 0.08,
      temperature: 0.38,
      tint: 0.06,
      vibrance: 0.28,
      saturation: 0.1,
      glowAmount: 0.25,
      grainAmount: 0.22,
      grainSize: 1.15,
      vignetteAmount: 0.18,
      lightLeakType: 'sunset',
      lightLeakAmount: 0.45,
      dateStamp: {
        enabled: true,
        style: 'led-orange',
        position: 'bottom-right',
        includeTime: true,
        size: 1.0,
        opacity: 0.95,
      },
    },
  },
  {
    id: 'template-sunbath-riviera',
    name: 'Riviera Bronze Sunbake',
    tag: 'sunbath',
    tagLabel: 'Sunbath',
    tagColor: '#D97706',
    tagBgColor: '#FFFBEB',
    subtitle: 'Rich terracotta warmth & sun-bleached coastal radiance',
    description: 'Deep chocolate undertones, warm terracotta highlights, subtle prism flare, and rich sun-baked saturation for beach and vacation vibes.',
    aspectRatio: 4 / 5,
    aspectLabel: '4:5 Portrait',
    moodKeywords: ['Riviera', 'Beach', 'Terracotta', 'Sunbaked', 'Glow'],
    previewThumbnail: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?q=80&w=800&auto=format&fit=crop',
    sampleMedia: {
      id: 'media-sunbath-2',
      name: 'Sunlit Coastal Shore',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?q=80&w=1200&auto=format&fit=crop',
      aspectRatio: 4 / 5,
      width: 1200,
      height: 1500,
    },
    adjustments: {
      ...defaultAdjustments,
      presetId: 'yum',
      exposure: 0.06,
      contrast: 0.22,
      highlights: -0.25,
      shadows: 0.2,
      temperature: 0.34,
      vibrance: 0.22,
      glowAmount: 0.18,
      grainAmount: 0.2,
      lightLeakType: 'side-flare',
      lightLeakAmount: 0.3,
      frameType: 'gallery-cream',
      frameWidth: 0.04,
    },
  },

  // ==========================================
  // 4. LOVE LETTERS
  // ==========================================
  {
    id: 'template-loveletters-rosewater',
    name: 'Dreamy Rosewater Love',
    tag: 'love letters',
    tagLabel: 'Love Letters',
    tagColor: '#DB2777',
    tagBgColor: '#FDF2F8',
    subtitle: 'Pastel pink blush tones & romantic soft focus dream haze',
    description: 'Soft romantic pastels with delicate rose and peach highlights, dreamy radial tilt-shift glow, fine organic grain, and intimate nostalgic mood.',
    aspectRatio: 4 / 5,
    aspectLabel: '4:5 Portrait',
    badge: 'Romantic',
    moodKeywords: ['Romantic', 'Pastel Pink', 'Dream Haze', 'Soft Focus', 'Blush'],
    previewThumbnail: 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?q=80&w=800&auto=format&fit=crop',
    sampleMedia: {
      id: 'media-loveletters-1',
      name: 'Pastel Bouquet & Sunlight',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?q=80&w=1200&auto=format&fit=crop',
      aspectRatio: 4 / 5,
      width: 1200,
      height: 1500,
    },
    adjustments: {
      ...defaultAdjustments,
      presetId: 'sugar',
      cameraType: 'pinky',
      exposure: 0.12,
      contrast: -0.08,
      highlights: -0.15,
      shadows: 0.25,
      temperature: 0.16,
      tint: 0.18,
      vibrance: 0.18,
      glowAmount: 0.35,
      blurAmount: 0.2,
      blurMode: 'radial',
      grainAmount: 0.16,
      grainSize: 1.0,
      lightLeakType: 'prism-beam',
      lightLeakAmount: 0.25,
      frameType: 'polaroid',
      frameWidth: 0.05,
      dateStamp: {
        enabled: true,
        style: 'film-gold',
        position: 'bottom-right',
        includeTime: false,
        size: 0.95,
        opacity: 0.9,
      },
    },
  },
  {
    id: 'template-loveletters-vintage',
    name: 'Nostalgic Romance 1996',
    tag: 'love letters',
    tagLabel: 'Love Letters',
    tagColor: '#DB2777',
    tagBgColor: '#FDF2F8',
    subtitle: 'Vintage heartthrob camcorder haze & sweet warm tones',
    description: 'Warm camcorder bloom with soft highlight halos, gentle pastel split toning, vintage film grain, and authentic camcorder date stamp.',
    aspectRatio: 3 / 4,
    aspectLabel: '3:4 Classic',
    moodKeywords: ['1996', 'Camcorder', 'Love Story', 'Sweet', 'Dreamy'],
    previewThumbnail: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=800&auto=format&fit=crop',
    sampleMedia: {
      id: 'media-loveletters-2',
      name: 'Sunset Lovers Silhouette',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=1200&auto=format&fit=crop',
      aspectRatio: 3 / 4,
      width: 1200,
      height: 1600,
    },
    adjustments: {
      ...defaultAdjustments,
      presetId: 'vintage',
      cameraType: 'camcorder',
      exposure: 0.08,
      contrast: 0.12,
      highlights: -0.2,
      shadows: 0.2,
      temperature: 0.22,
      tint: 0.12,
      glowAmount: 0.28,
      grainAmount: 0.25,
      dustType: 'fine-specks',
      dustAmount: 0.2,
      dateStamp: {
        enabled: true,
        style: 'camcorder-green',
        position: 'bottom-left',
        includeTime: true,
        customDate: '1996-08-30',
        size: 1.0,
        opacity: 0.95,
      },
    },
  },

  // ==========================================
  // 5. FILM CLASSIC
  // ==========================================
  {
    id: 'template-filmclassic-portra',
    name: 'LumenLab 35mm Portra 400',
    tag: 'film classic',
    tagLabel: 'Film Classic',
    tagColor: '#92400E',
    tagBgColor: '#FDE68A',
    subtitle: 'Iconic analog emulsion, organic grain & corner burn',
    description: 'The definitive classic 35mm analog film aesthetic with rich Kodak Portra color response, gentle highlight rolloff, corner burn leak, and 35mm sprocket border.',
    aspectRatio: 2 / 3,
    aspectLabel: '2:3 35mm Film',
    badge: 'Iconic',
    moodKeywords: ['35mm Film', 'Portra 400', 'Analog', 'Timeless', 'Kodak'],
    previewThumbnail: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop',
    sampleMedia: {
      id: 'media-filmclassic-1',
      name: 'Editorial Analog Portrait',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1200&auto=format&fit=crop',
      aspectRatio: 4 / 5,
      width: 1200,
      height: 1500,
    },
    adjustments: {
      ...defaultAdjustments,
      presetId: 'portra',
      cameraType: 'kodak-gold',
      exposure: 0.06,
      contrast: 0.16,
      highlights: -0.22,
      shadows: 0.18,
      temperature: 0.24,
      tint: 0.04,
      vibrance: 0.16,
      grainAmount: 0.35,
      grainSize: 1.2,
      lightLeakType: 'corner-burn',
      lightLeakAmount: 0.32,
      dustType: 'fine-specks',
      dustAmount: 0.15,
      frameType: 'film-35mm',
      frameWidth: 0.055,
      dateStamp: {
        enabled: true,
        style: 'led-orange',
        position: 'bottom-right',
        includeTime: false,
        size: 1.0,
        opacity: 0.95,
      },
    },
  },
  {
    id: 'template-filmclassic-halide',
    name: '1970s Silver Halide',
    tag: 'film classic',
    tagLabel: 'Film Classic',
    tagColor: '#92400E',
    tagBgColor: '#FDE68A',
    subtitle: 'Rich organic film emulsion & authentic Kodachrome tones',
    description: 'Deep analog shadow tones, vintage yellow-amber warmth, organic silver halide grain texture, and 120mm slide mount framing.',
    aspectRatio: 4 / 5,
    aspectLabel: '4:5 Portrait',
    moodKeywords: ['1970s', 'Silver Halide', 'Kodachrome', 'Grainy', 'Slide 120'],
    previewThumbnail: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=800&auto=format&fit=crop',
    sampleMedia: {
      id: 'media-filmclassic-2',
      name: 'Bohemian Sunlit Meadow',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=1200&auto=format&fit=crop',
      aspectRatio: 4 / 5,
      width: 1200,
      height: 1500,
    },
    adjustments: {
      ...defaultAdjustments,
      presetId: 'gold',
      cameraType: 'solare17',
      exposure: 0.04,
      contrast: 0.2,
      highlights: -0.28,
      shadows: 0.16,
      temperature: 0.28,
      tint: -0.04,
      vibrance: 0.18,
      grainAmount: 0.4,
      grainSize: 1.3,
      dustType: 'film-scratches',
      dustAmount: 0.22,
      frameType: 'slide-120',
      frameWidth: 0.05,
    },
  },

  // ==========================================
  // 6. FILM WHITE
  // ==========================================
  {
    id: 'template-filmwhite-milky',
    name: 'Milky White Film Glow',
    tag: 'film white',
    tagLabel: 'Film White',
    tagColor: '#475569',
    tagBgColor: '#F1F5F9',
    subtitle: 'High-key milky whites, gentle contrast lift & soft film bloom',
    description: 'High-fashion editorial white film look with elevated black levels, soft glowing highlights, subdued saturation, and crisp gallery matting.',
    aspectRatio: 4 / 5,
    aspectLabel: '4:5 Portrait',
    badge: 'Trendy',
    moodKeywords: ['Milky Whites', 'High-Key', 'Bloom', 'Luxe', 'Matte'],
    previewThumbnail: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop',
    sampleMedia: {
      id: 'media-filmwhite-1',
      name: 'High Fashion Studio Silhouette',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1200&auto=format&fit=crop',
      aspectRatio: 4 / 5,
      width: 1200,
      height: 1500,
    },
    adjustments: {
      ...defaultAdjustments,
      presetId: 'cream',
      exposure: 0.15,
      contrast: -0.12,
      highlights: -0.15,
      shadows: 0.3,
      whites: 0.18,
      blacks: 0.22,
      temperature: 0.04,
      tint: 0.02,
      vibrance: -0.05,
      glowAmount: 0.3,
      grainAmount: 0.15,
      frameType: 'gallery-white',
      frameWidth: 0.06,
      dateStamp: {
        enabled: true,
        style: 'classic-white',
        position: 'bottom-right',
        includeTime: false,
        size: 0.9,
        opacity: 0.8,
      },
    },
  },
  {
    id: 'template-filmwhite-linen',
    name: 'Linen & Lace Aesthetic',
    tag: 'film white',
    tagLabel: 'Film White',
    tagColor: '#475569',
    tagBgColor: '#F1F5F9',
    subtitle: 'Subtle warm linen undertones & luminous editorial softness',
    description: 'Airy highlights with soft linen warmth, lifted shadows, gentle film grain, and warm linen cream border.',
    aspectRatio: 1 / 1,
    aspectLabel: '1:1 Square',
    moodKeywords: ['Linen', 'Lace', 'Airy', 'Chic', 'Cream'],
    previewThumbnail: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=800&auto=format&fit=crop',
    sampleMedia: {
      id: 'media-filmwhite-2',
      name: 'Linen Dress & Soft Shadows',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1200&auto=format&fit=crop',
      aspectRatio: 3 / 4,
      width: 1200,
      height: 1600,
    },
    adjustments: {
      ...defaultAdjustments,
      presetId: 'almond',
      exposure: 0.12,
      contrast: -0.06,
      highlights: -0.18,
      shadows: 0.25,
      temperature: 0.12,
      tint: 0.04,
      glowAmount: 0.2,
      grainAmount: 0.12,
      frameType: 'gallery-cream',
      frameWidth: 0.05,
    },
  },

  // ==========================================
  // 7. EDITORIAL
  // ==========================================
  {
    id: 'template-editorial-vogue',
    name: 'Vogue Cover Lookbook',
    tag: 'editorial',
    tagLabel: 'Editorial',
    tagColor: '#18181B',
    tagBgColor: '#E4E4E7',
    subtitle: 'High-fashion stark contrast, deep blacks & bold drama',
    description: 'High-contrast fashion magazine grading with punchy clarity, deep inky blacks, sculpted cheekbone highlights, and stark editorial framing.',
    aspectRatio: 4 / 5,
    aspectLabel: '4:5 Portrait',
    badge: 'Pro Editorial',
    moodKeywords: ['Vogue', 'High Fashion', 'Dramatic', 'Sharp', 'Bold'],
    previewThumbnail: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=800&auto=format&fit=crop',
    sampleMedia: {
      id: 'media-editorial-1',
      name: 'High Fashion Runway Look',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1200&auto=format&fit=crop',
      aspectRatio: 4 / 5,
      width: 1200,
      height: 1500,
    },
    adjustments: {
      ...defaultAdjustments,
      presetId: 'editorial',
      exposure: 0.04,
      contrast: 0.32,
      highlights: -0.18,
      shadows: 0.1,
      whites: 0.15,
      blacks: -0.18,
      temperature: -0.05,
      tint: 0.04,
      vibrance: 0.2,
      clarity: 0.35,
      grainAmount: 0.18,
      vignetteAmount: 0.22,
      frameType: 'gallery-white',
      frameWidth: 0.04,
    },
  },
  {
    id: 'template-editorial-paris',
    name: 'Paris Haute Couture',
    tag: 'editorial',
    tagLabel: 'Editorial',
    tagColor: '#18181B',
    tagBgColor: '#E4E4E7',
    subtitle: 'Muted olive greens, desaturated blues & chic runway tones',
    description: 'Sophisticated Parisian palette with muted environmental greens, glowing skin tones, subtle highlight glow, and sleek 9:16 layout.',
    aspectRatio: 9 / 16,
    aspectLabel: '9:16 Story / Reel',
    moodKeywords: ['Haute Couture', 'Parisian', 'Muted Greens', 'Chic', 'Runway'],
    previewThumbnail: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?q=80&w=800&auto=format&fit=crop',
    sampleMedia: {
      id: 'media-editorial-2',
      name: 'Parisian Runway Streetstyle',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?q=80&w=1200&auto=format&fit=crop',
      aspectRatio: 9 / 16,
      width: 1080,
      height: 1920,
    },
    adjustments: {
      ...defaultAdjustments,
      presetId: 'cinema',
      cameraType: 'klasse',
      exposure: 0.06,
      contrast: 0.24,
      highlights: -0.22,
      shadows: 0.15,
      temperature: 0.08,
      tint: -0.06,
      vibrance: 0.12,
      glowAmount: 0.18,
      grainAmount: 0.22,
      vignetteAmount: 0.2,
      frameType: 'gallery-white',
      frameWidth: 0.035,
    },
  },

  // ==========================================
  // 8. SKETCH
  // ==========================================
  {
    id: 'template-sketch-charcoal',
    name: 'Artistic Charcoal & Grain',
    tag: 'sketch',
    tagLabel: 'Sketch',
    tagColor: '#52525B',
    tagBgColor: '#F4F4F5',
    subtitle: 'Deep textured monochrome & raw analog drawing mood',
    description: 'Heavy tactile film grain with dramatic tonal curve, rich charcoal shadow depth, fine dust specks, and raw artistic aesthetic.',
    aspectRatio: 4 / 5,
    aspectLabel: '4:5 Portrait',
    badge: 'Artistic',
    moodKeywords: ['Charcoal', 'B&W', 'Heavy Grain', 'Artistic', 'Drawing'],
    previewThumbnail: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=800&auto=format&fit=crop',
    sampleMedia: {
      id: 'media-sketch-1',
      name: 'Charcoal Dramatic Portrait',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=1200&auto=format&fit=crop',
      aspectRatio: 4 / 5,
      width: 1200,
      height: 1500,
    },
    adjustments: {
      ...defaultAdjustments,
      presetId: 'noir',
      cameraType: 'ilford',
      exposure: 0.04,
      contrast: 0.38,
      highlights: -0.3,
      shadows: 0.12,
      whites: 0.2,
      blacks: -0.22,
      saturation: -1.0,
      vibrance: -1.0,
      clarity: 0.4,
      grainAmount: 0.48,
      grainSize: 1.4,
      dustType: 'film-scratches',
      dustAmount: 0.35,
      vignetteAmount: 0.3,
      frameType: 'gallery-white',
      frameWidth: 0.05,
    },
  },
  {
    id: 'template-sketch-sepia',
    name: 'Warm Sepia Paper Sketch',
    tag: 'sketch',
    tagLabel: 'Sketch',
    tagColor: '#52525B',
    tagBgColor: '#F4F4F5',
    subtitle: 'Antique handmade paper wash & handcrafted pencil mood',
    description: 'Antique sepia paper wash with soft warm shadows, heavy organic grain, light scratches, and nostalgic vintage TV curvature framing.',
    aspectRatio: 1 / 1,
    aspectLabel: '1:1 Square',
    moodKeywords: ['Sepia', 'Paper Wash', 'Vintage', 'Pencil Mood'],
    previewThumbnail: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=800&auto=format&fit=crop',
    sampleMedia: {
      id: 'media-sketch-2',
      name: 'Warm Paper Texture Portrait',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=1200&auto=format&fit=crop',
      aspectRatio: 1 / 1,
      width: 1200,
      height: 1200,
    },
    adjustments: {
      ...defaultAdjustments,
      presetId: 'sepia',
      exposure: 0.06,
      contrast: 0.18,
      highlights: -0.22,
      shadows: 0.24,
      temperature: 0.45,
      tint: 0.12,
      saturation: -0.3,
      grainAmount: 0.42,
      grainSize: 1.3,
      dustType: 'vintage-dust',
      dustAmount: 0.28,
      frameType: 'retro-tv',
      frameWidth: 0.06,
    },
  },

  // ==========================================
  // 9. CYBER
  // ==========================================
  {
    id: 'template-cyber-hologram',
    name: 'Y2K Cyber Hologram',
    tag: 'cyber',
    tagLabel: 'Cyber',
    tagColor: '#0284C7',
    tagBgColor: '#E0F2FE',
    subtitle: 'Chromatic aberration, VHS scanlines & cyan-magenta neon',
    description: 'Futuristic Y2K cyber aesthetic with chromatic RGB split shift, CRT scanline overlay, glowing cyan/magenta split tones, and retro green camcorder date stamp.',
    aspectRatio: 9 / 16,
    aspectLabel: '9:16 Story / Reel',
    badge: 'Futuristic',
    moodKeywords: ['Y2K', 'Cyberpunk', 'VHS', 'Chromatic', 'Neon'],
    previewThumbnail: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?q=80&w=800&auto=format&fit=crop',
    sampleMedia: {
      id: 'media-cyber-1',
      name: 'Neon Cyber Skyline',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?q=80&w=1200&auto=format&fit=crop',
      aspectRatio: 9 / 16,
      width: 1080,
      height: 1920,
    },
    adjustments: {
      ...defaultAdjustments,
      presetId: 'cyber',
      cameraType: 'vhs',
      exposure: 0.08,
      contrast: 0.28,
      highlights: -0.15,
      shadows: 0.18,
      temperature: -0.25,
      tint: 0.35,
      saturation: 0.25,
      vibrance: 0.35,
      prismAmount: 0.45,
      vhsAmount: 0.38,
      glowAmount: 0.3,
      grainAmount: 0.28,
      dateStamp: {
        enabled: true,
        style: 'camcorder-green',
        position: 'top-left',
        includeTime: true,
        size: 1.05,
        opacity: 0.95,
      },
    },
  },
  {
    id: 'template-cyber-tokyo',
    name: 'Tokyo Neon Cyberpunk',
    tag: 'cyber',
    tagLabel: 'Cyber',
    tagColor: '#0284C7',
    tagBgColor: '#E0F2FE',
    subtitle: 'Vibrant electric blues, violet shadows & side beam flares',
    description: 'Electric Tokyo night grading with deep indigo shadows, saturated cyan reflections, prism side flare beam, and retro TV framing.',
    aspectRatio: 16 / 9,
    aspectLabel: '16:9 Cinema / Video',
    moodKeywords: ['Tokyo', 'Neon', 'Prism Beam', 'Electric', 'Sci-Fi'],
    previewThumbnail: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?q=80&w=800&auto=format&fit=crop',
    sampleMedia: {
      id: 'media-cyber-2',
      name: 'Tokyo Rain Neon Crosswalk',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?q=80&w=1200&auto=format&fit=crop',
      aspectRatio: 16 / 9,
      width: 1200,
      height: 675,
    },
    adjustments: {
      ...defaultAdjustments,
      presetId: 'cyber',
      exposure: 0.04,
      contrast: 0.3,
      temperature: -0.3,
      tint: 0.25,
      vibrance: 0.4,
      lightLeakType: 'prism-beam',
      lightLeakAmount: 0.4,
      prismAmount: 0.35,
      vhsAmount: 0.25,
      frameType: 'retro-tv',
      frameWidth: 0.04,
    },
  },

  // ==========================================
  // 10. PRIDE
  // ==========================================
  {
    id: 'template-pride-rainbow',
    name: 'Rainbow Chromatic Glow',
    tag: 'pride',
    tagLabel: 'Pride',
    tagColor: '#7C3AED',
    tagBgColor: '#F3E8FF',
    subtitle: 'Joyful multi-hue saturation & sparkling prism beam radiance',
    description: 'Celebratory high-energy palette with vibrant rainbow spectrum saturation, glowing multi-hue prism flare, boosted vibrance, and clean white editorial frame.',
    aspectRatio: 4 / 5,
    aspectLabel: '4:5 Portrait',
    badge: 'Vibrant',
    moodKeywords: ['Pride', 'Rainbow', 'Joyful', 'Spectrum', 'Prism Flare'],
    previewThumbnail: 'https://images.unsplash.com/photo-1561055657-b9e0bf0fa360?q=80&w=800&auto=format&fit=crop',
    sampleMedia: {
      id: 'media-pride-1',
      name: 'Pride Festival Color Splash',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1561055657-b9e0bf0fa360?q=80&w=1200&auto=format&fit=crop',
      aspectRatio: 4 / 5,
      width: 1200,
      height: 1500,
    },
    adjustments: {
      ...defaultAdjustments,
      presetId: 'poppy',
      exposure: 0.1,
      contrast: 0.18,
      highlights: -0.15,
      shadows: 0.2,
      whites: 0.1,
      blacks: 0.05,
      temperature: 0.05,
      tint: 0.08,
      saturation: 0.28,
      vibrance: 0.38,
      glowAmount: 0.25,
      lightLeakType: 'prism-beam',
      lightLeakAmount: 0.45,
      grainAmount: 0.15,
      frameType: 'gallery-white',
      frameWidth: 0.045,
      dateStamp: {
        enabled: true,
        style: 'y2k-yellow',
        position: 'bottom-right',
        includeTime: false,
        size: 0.95,
        opacity: 0.9,
      },
    },
  },
  {
    id: 'template-pride-disco',
    name: 'Sunlit Spectrum Disco',
    tag: 'pride',
    tagLabel: 'Pride',
    tagColor: '#7C3AED',
    tagBgColor: '#F3E8FF',
    subtitle: 'Golden chromatic celebration & high-energy festival pop',
    description: 'Rich sunset glow infused with vivid rainbow split-hues, radiant skin illumination, retro flare bursts, and Polaroid instant border.',
    aspectRatio: 9 / 16,
    aspectLabel: '9:16 Story / Reel',
    moodKeywords: ['Festival', 'Disco', 'Celebration', 'Pop', 'Energy'],
    previewThumbnail: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?q=80&w=800&auto=format&fit=crop',
    sampleMedia: {
      id: 'media-pride-2',
      name: 'Sunlit Festival Confetti',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?q=80&w=1200&auto=format&fit=crop',
      aspectRatio: 9 / 16,
      width: 1080,
      height: 1920,
    },
    adjustments: {
      ...defaultAdjustments,
      presetId: 'sol',
      exposure: 0.12,
      contrast: 0.22,
      highlights: -0.2,
      shadows: 0.22,
      temperature: 0.18,
      tint: 0.14,
      saturation: 0.22,
      vibrance: 0.32,
      glowAmount: 0.3,
      lightLeakType: 'sunset',
      lightLeakAmount: 0.4,
      frameType: 'polaroid',
      frameWidth: 0.05,
    },
  },
  // ==========================================
  // COLLAGE & STORY TEMPLATES (From Uploaded Reference Designs)
  // ==========================================
  ...COLLAGE_TEMPLATES.map((col): ProjectTemplate => {
    const tag: ProjectTemplateTag =
      col.category === 'airdrop'
        ? 'airdrop'
        : col.category === 'notebook'
        ? 'notebook'
        : col.category === 'scrapbook'
        ? 'scrapbook'
        : col.category === 'polaroid-stack'
        ? 'polaroid'
        : col.category === 'editorial-grid'
        ? 'bento'
        : col.category === 'handwritten-story'
        ? 'handwritten'
        : 'clean';

    return {
      id: col.id,
      name: col.name,
      tag,
      tagLabel: col.categoryLabel,
      tagColor: '#2A2723',
      tagBgColor: '#F5F2EB',
      subtitle: col.subtitle,
      description: col.description,
      aspectRatio: col.aspectRatio,
      aspectLabel: col.aspectLabel,
      badge: col.badge,
      moodKeywords: col.moodKeywords,
      previewThumbnail: col.previewThumbnail,
      sampleMedia: col.slots[0]?.media || {
        id: `media-${col.id}`,
        name: col.name,
        type: 'image',
        url: col.previewThumbnail,
        aspectRatio: col.aspectRatio,
        width: 1080,
        height: 1920,
      },
      adjustments: col.adjustments,
      collageData: col,
    };
  }),
];

