import { MarketplaceProject } from '../types';
import { LUMENLAB_PROJECT_TEMPLATES } from './projectTemplates';
import { safeClone } from '../utils/safeClone';

// Curated initial seed marketplace projects created by the community
export const SEED_MARKETPLACE_PROJECTS: MarketplaceProject[] = [
  {
    id: 'market_tokyo_portra',
    originalProjectId: 'tpl-film-street',
    creatorId: 'creator_tokyo_grain',
    creatorName: 'Elena Rostova',
    creatorPhotoURL: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    name: 'Tokyo 35mm Portra 400',
    description: 'Nostalgic golden-hour 35mm street simulation with warm halation, analog film grain, and retro date stamp.',
    templateId: 'tpl-film-street',
    templateTag: 'film classic',
    aspectRatio: 4 / 5,
    media: LUMENLAB_PROJECT_TEMPLATES[4]?.sampleMedia || {
      id: 'seed_media_1',
      name: 'Tokyo Night.jpg',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&auto=format&fit=crop&q=80',
      aspectRatio: 4 / 5,
      width: 1200,
      height: 1500,
    },
    adjustments: LUMENLAB_PROJECT_TEMPLATES[4]?.adjustments || safeClone(LUMENLAB_PROJECT_TEMPLATES[0].adjustments),
    collages: LUMENLAB_PROJECT_TEMPLATES[4]?.collageData ? [safeClone(LUMENLAB_PROJECT_TEMPLATES[4].collageData)] : undefined,
    activeCollage: LUMENLAB_PROJECT_TEMPLATES[4]?.collageData ? safeClone(LUMENLAB_PROJECT_TEMPLATES[4].collageData) : undefined,
    activeCollageIndex: 0,
    replicationCount: 168,
    publishedAt: Date.now() - 1000 * 60 * 60 * 24 * 7,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 7,
    updatedAt: Date.now() - 1000 * 60 * 60 * 12,
    badge: 'Trending #1',
  },
  {
    id: 'market_airdrop_editorial',
    originalProjectId: 'tpl-airdrop-share',
    creatorId: 'creator_julian_vance',
    creatorName: 'Julian Vance Studio',
    creatorPhotoURL: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    name: 'AirDrop Storyboard Capsule',
    description: 'Editorial collage layout with authentic iOS AirDrop modal prompt, paper textures, and curated film strip.',
    templateId: 'tpl-airdrop-share',
    templateTag: 'souveniers',
    aspectRatio: 9 / 16,
    media: LUMENLAB_PROJECT_TEMPLATES[1]?.sampleMedia || {
      id: 'seed_media_2',
      name: 'AirDrop Editorial.jpg',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=1200&auto=format&fit=crop&q=80',
      aspectRatio: 9 / 16,
      width: 1080,
      height: 1920,
    },
    adjustments: LUMENLAB_PROJECT_TEMPLATES[1]?.adjustments || safeClone(LUMENLAB_PROJECT_TEMPLATES[0].adjustments),
    collages: LUMENLAB_PROJECT_TEMPLATES[1]?.collageData ? [safeClone(LUMENLAB_PROJECT_TEMPLATES[1].collageData)] : undefined,
    activeCollage: LUMENLAB_PROJECT_TEMPLATES[1]?.collageData ? safeClone(LUMENLAB_PROJECT_TEMPLATES[1].collageData) : undefined,
    activeCollageIndex: 0,
    replicationCount: 142,
    publishedAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
    updatedAt: Date.now() - 1000 * 60 * 60 * 6,
    badge: 'Popular',
  },
  {
    id: 'market_notebook_scrapbook',
    originalProjectId: 'tpl-spiral-notebook',
    creatorId: 'creator_chloe_b',
    creatorName: 'Chloe Bennett',
    creatorPhotoURL: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    name: 'Vintage Spiral Notebook Diary',
    description: 'Realistic metallic binder ring collage with kraft paper backing, handwritten scrawls, and polaroid tape.',
    templateId: 'tpl-spiral-notebook',
    templateTag: 'love letters',
    aspectRatio: 4 / 5,
    media: LUMENLAB_PROJECT_TEMPLATES[3]?.sampleMedia || {
      id: 'seed_media_3',
      name: 'Notebook Spread.jpg',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=1200&auto=format&fit=crop&q=80',
      aspectRatio: 4 / 5,
      width: 1200,
      height: 1500,
    },
    adjustments: LUMENLAB_PROJECT_TEMPLATES[3]?.adjustments || safeClone(LUMENLAB_PROJECT_TEMPLATES[0].adjustments),
    collages: LUMENLAB_PROJECT_TEMPLATES[3]?.collageData ? [safeClone(LUMENLAB_PROJECT_TEMPLATES[3].collageData)] : undefined,
    activeCollage: LUMENLAB_PROJECT_TEMPLATES[3]?.collageData ? safeClone(LUMENLAB_PROJECT_TEMPLATES[3].collageData) : undefined,
    activeCollageIndex: 0,
    replicationCount: 119,
    publishedAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
    updatedAt: Date.now() - 1000 * 60 * 60 * 18,
    badge: 'Featured',
  },
  {
    id: 'market_sunbath_leaks',
    originalProjectId: 'tpl-sunbath-golden',
    creatorId: 'creator_mateo_silva',
    creatorName: 'Mateo Silva',
    creatorPhotoURL: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    name: 'Sunbath Warm Amber Glow',
    description: 'Radiant golden hour grading with amber light leak overlays, warm skin tone preservation, and soft fade.',
    templateId: 'tpl-sunbath-golden',
    templateTag: 'sunbath',
    aspectRatio: 4 / 5,
    media: LUMENLAB_PROJECT_TEMPLATES[2]?.sampleMedia || {
      id: 'seed_media_4',
      name: 'Sunbath Beach.jpg',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80',
      aspectRatio: 4 / 5,
      width: 1200,
      height: 1500,
    },
    adjustments: LUMENLAB_PROJECT_TEMPLATES[2]?.adjustments || safeClone(LUMENLAB_PROJECT_TEMPLATES[0].adjustments),
    collages: LUMENLAB_PROJECT_TEMPLATES[2]?.collageData ? [safeClone(LUMENLAB_PROJECT_TEMPLATES[2].collageData)] : undefined,
    activeCollage: LUMENLAB_PROJECT_TEMPLATES[2]?.collageData ? safeClone(LUMENLAB_PROJECT_TEMPLATES[2].collageData) : undefined,
    activeCollageIndex: 0,
    replicationCount: 94,
    publishedAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
    updatedAt: Date.now() - 1000 * 60 * 60 * 8,
  },
  {
    id: 'market_minimal_clean_grid',
    originalProjectId: 'tpl-clean-editorial',
    creatorId: 'creator_studio_nord',
    creatorName: 'Studio Nordik',
    creatorPhotoURL: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    name: 'Minimalist Clean White Dual-Frame',
    description: 'High-key studio contrast with sleek margins, pure neutral duotone balance, and sans-serif typography.',
    templateId: 'tpl-clean-editorial',
    templateTag: 'clean',
    aspectRatio: 1,
    media: LUMENLAB_PROJECT_TEMPLATES[0]?.sampleMedia || {
      id: 'seed_media_5',
      name: 'Minimalist Architecture.jpg',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&auto=format&fit=crop&q=80',
      aspectRatio: 1,
      width: 1200,
      height: 1200,
    },
    adjustments: LUMENLAB_PROJECT_TEMPLATES[0]?.adjustments || safeClone(LUMENLAB_PROJECT_TEMPLATES[0].adjustments),
    collages: LUMENLAB_PROJECT_TEMPLATES[0]?.collageData ? [safeClone(LUMENLAB_PROJECT_TEMPLATES[0].collageData)] : undefined,
    activeCollage: LUMENLAB_PROJECT_TEMPLATES[0]?.collageData ? safeClone(LUMENLAB_PROJECT_TEMPLATES[0].collageData) : undefined,
    activeCollageIndex: 0,
    replicationCount: 78,
    publishedAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
    updatedAt: Date.now() - 1000 * 60 * 60 * 4,
  },
];
